
import { Service, Product, Staff, Expense, Customer, DiscountCode, ShopSettings, Language } from './types';

export const CURRENCY_OPTIONS = [
  { label: 'US Dollar ($)', symbol: '$' },
  { label: 'Euro (€)', symbol: '€' },
  { label: 'British Pound (£)', symbol: '£' },
  { label: 'Pakistani Rupee (Rs.)', symbol: 'Rs.' },
  { label: 'Indian Rupee (₹)', symbol: '₹' },
  { label: 'UAE Dirham (د.إ)', symbol: 'د.إ' },
  { label: 'Saudi Riyal (ر.س)', symbol: 'ر.س' },
  { label: 'Canadian Dollar (C$)', symbol: 'C$' },
  { label: 'Australian Dollar (A$)', symbol: 'A$' },
];

export const COUNTRY_CODES = [
  { code: '+1', label: 'US/Canada (+1)' },
  { code: '+44', label: 'UK (+44)' },
  { code: '+92', label: 'Pakistan (+92)' },
  { code: '+91', label: 'India (+91)' },
  { code: '+971', label: 'UAE (+971)' },
  { code: '+966', label: 'Saudi Arabia (+966)' },
  { code: '+61', label: 'Australia (+61)' },
  { code: '+49', label: 'Germany (+49)' },
  { code: '+33', label: 'France (+33)' },
  { code: '+90', label: 'Turkey (+90)' },
  { code: '+20', label: 'Egypt (+20)' },
];

export const INITIAL_DISCOUNT_CODES: DiscountCode[] = [
  { code: 'WELCOME10', type: 'percentage', value: 10, description: '10% off for new customers' },
  { code: 'VIP20', type: 'percentage', value: 20, description: '20% off for VIP members' },
  { code: 'SAVE5', type: 'fixed', value: 5, description: '$5 off total' },
];

export const DEFAULT_SETTINGS: ShopSettings = {
  shopName: 'My Business',
  currency: '$',
  language: 'en',
  countryCode: '+1',
  whatsappEnabled: true,
  whatsappNumber: '',
  receiptFooter: 'Thank you for choosing us!',
  taxRate: 8,
  taxType: 'excluded',
  billingCycleDay: 1,
  promoCodes: INITIAL_DISCOUNT_CODES,
  deductExpensesFromCommission: false,
  loyaltyEnabled: true,
  pointsPerCurrency: 1,
  minPointsToRedeem: 100,
  bookingEnabled: false,
  bookingSlug: ''
};

export const TRANSLATIONS = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    pos: 'POS Terminal',
    catalog: 'Catalog',
    customers: 'Customers',
    staff: 'Staff Management',
    finance: 'Finances',
    settings: 'Settings',
    appointments: 'Appointments',
    logout: 'Logout',
    shopStatus: 'Shop Status',
    terminalLive: 'Terminal Live',
    transactionHistory: 'Transaction History',
    
    // Dashboard
    performanceInsights: 'Performance Insights',
    welcomeBack: "Welcome back! Here's what's happening in your shop.",
    revenue: 'Revenue',
    expenses: 'Expenses',
    netProfit: 'Net Profit',
    avgTicket: 'Avg Ticket',
    revenueTrends: 'Revenue Trends',
    recentTransactions: 'Recent Transactions',
    waitingForSale: 'Waiting for first sale...',
    last7Days: 'Last 7 Days',
    today: 'Today',
    week: 'This Week',
    month: 'This Month',
    all: 'All Time',
    custom: 'Custom Range',
    lowStockAlerts: 'Low Stock Alerts',
    itemsRestock: 'items need restocking',
    restockNow: 'Restock Now',
    inventoryValue: 'Inventory Value',
    payroll: 'Payroll',
    remainingBalance: 'Remaining Balance',
    topPerformers: 'Top Performers',
    topServices: 'Top Services',
    topProducts: 'Top Products',
    staffLeaderboard: 'Staff Leaderboard',
    expenseBreakdown: 'Expense Breakdown',
    alertQty: 'Alert Qty',
    noRecords: 'No records found.',

    // POS
    services: 'Services',
    products: 'Products',
    searchCatalog: 'Search catalog...',
    scanBarcode: 'Scan Barcode',
    stopScanning: 'Stop Scanning',
    cart: 'Cart',
    emptyCart: 'Empty Cart',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    cash: 'Cash',
    card: 'Card',
    holdBill: 'Hold Bill',
    heldBills: 'Held Bills',
    resume: 'Resume',
    saleSuccess: 'Sale Success',
    orderCompleted: 'Order completed.',
    shareReceipt: 'Share Receipt',
    downloadPdf: 'Download PDF',
    startNewBill: 'Start New Bill',
    chooseProfessional: 'Choose Professional...',
    walkInClient: 'Walk-in Client',
    quickAddClient: 'Quick Add Client',
    addSelectClient: 'Add & Select Client',
    name: 'Name',
    nameUr: 'Name (Urdu)',
    mobile: 'Mobile',
    email: 'Email',
    optional: 'Optional',

    // Finance
    shopPerformance: 'Shop Performance',
    commissionReport: 'Commission Report',
    payrollReport: 'Generate payroll reports by date range.',
    newExpense: 'New Expense',
    history: 'History',
    periodRevenue: 'Period Revenue',
    totalPayout: 'Total Payout',
    professional: 'Professional',
    salesCount: 'Sales Count',
    totalSales: 'Total Sales',
    payout: 'Payout',
    rate: 'Rate',
    category: 'Category',
    amount: 'Amount',
    details: 'Details',
    addExpense: 'Add Expense',
    smartInsights: 'Smart AI Insights',
    generateAdvice: 'Generate Advice',
    analyzing: 'Analyzing...',
    aiPrompt: 'Tap "Generate Advice" for a personalized business analysis.',
    noSalesPeriod: 'No sales found in this period.',
    noteDetails: 'Note down any details...',
    exportReports: 'Export Reports',
    downloadDaily: 'Download Daily',
    downloadWeekly: 'Download Weekly',
    downloadMonthly: 'Download Monthly',

    // Customers
    directory: 'Directory',
    clientProfiles: 'Client profiles and history.',
    addClient: 'Add Client',
    searchClients: 'Search clients...',
    visits: 'Visits',
    lifetime: 'Lifetime',
    lastSeen: 'Last Seen',
    stylePreferences: 'Style Preferences',
    noNotes: 'No notes on file.',
    date: 'Date',
    items: 'Items',
    registerClient: 'Register Client',
    createProfile: 'Create Profile',
    pickClient: 'Pick a client to review their grooming history.',
    member: 'Member',
    vip: 'VIP',

    // Staff
    teamHub: 'Team Hub',
    manageAccess: 'Manage access and earnings.',
    addStaff: 'Add Staff',
    loginId: 'Login ID',
    role: 'Role',
    commission: 'Commission',
    actions: 'Actions',
    editProfessional: 'Edit Professional',
    addToTeam: 'Add to Team',
    fullName: 'Full Name',
    username: 'Username',
    password: 'Password',
    employee: 'Employee',
    admin: 'Admin',
    saveProfessional: 'Save Professional',
    updateProfessional: 'Update Professional',

    // Inventory
    shopCatalog: 'Shop Catalog',
    updatePrices: 'Update prices and stock.',
    newService: 'New Service',
    newProduct: 'New Product',
    inventory: 'Inventory',
    itemDetails: 'Item Details',
    stockStatus: 'Stock Status',
    price: 'Price',
    editEntry: 'Edit Entry',
    newEntry: 'New Entry',
    labelName: 'Label Name',
    barcode: 'Barcode',
    mins: 'Mins',
    cost: 'Cost',
    initialStock: 'Initial Stock',
    saveChanges: 'Save Changes',
    unitsLeft: 'Units left',
    session: 'session',

    // Settings
    fineTune: 'Fine-tune your shop and communications.',
    shopBranding: 'Shop Branding & Localization',
    terminalIdentity: 'Terminal Identity',
    language: 'Language',
    countryCode: 'Default Country Code',
    preferredCurrency: 'Preferred Currency',
    taxCalculation: 'Tax Calculation',
    taxRate: 'Tax Rate (%)',
    receiptFooter: 'Receipt Footer',
    whatsAppSummaries: 'WhatsApp Summaries',
    enableWhatsApp: 'Enable digital receipts via WhatsApp.',
    businessMobile: 'Business Mobile Number',
    resetChanges: 'Reset Changes',
    saveSettings: 'Save All Settings',
    excluded: 'Excluded',
    included: 'Included',
    customSymbol: 'Custom symbol...',
    billingCycle: 'Billing Cycle',
    billingDay: 'Start Day of Month',
    dangerZone: 'Danger Zone',
    resetSales: 'Reset Sales History',
    resetSalesDesc: 'Permanently delete all sales history. This cannot be undone.',
    confirmReset: 'Are you absolutely sure you want to delete all sales records?',
    promoCodes: 'Promo Codes & Coupons',
    addPromo: 'Add Promo Code',
    code: 'Code',
    discountType: 'Discount Type',
    value: 'Value',
    description: 'Description',
    fixed: 'Fixed Amount',
    percentage: 'Percentage (%)',
    deductExpenses: 'Deduct Shop Expenses from Commission',
    deductExpensesDesc: 'If enabled, total shop expenses will be subtracted from revenue before calculating staff commissions.',
    advancePayments: 'Advance Payments',
    addAdvance: 'Add Advance',
    payoutSummary: 'Payout Summary',
    netCommission: 'Net Commission',
    totalAdvances: 'Total Advances',
    finalPayout: 'Final Payout',
    // New translations
    searchRefund: "Search Sale ID for Refund...",
    splitPayment: "Split Payment",
    holdResume: "Hold/Resume",
    refunds: "Refunds",
    loyaltyPoints: "Loyalty Points",
    suppliers: "Suppliers",
    onlineBooking: "Online Booking",
    bookingSlug: "Booking Link Slug",
    enableBooking: "Enable Public Booking Page",
    copyBookingLink: "Copy Booking Link",
    bookingLinkCopied: "Booking link copied!",
    approvalQueue: "Approval Queue",
    confirmBooking: "Confirm Booking",
    declineBooking: "Decline Booking",
    bookingStatusUnconfirmed: "Waiting for Approval",
    bookingStatusConfirmed: "Confirmed",
    cashDrawer: "Cash Drawer",
    staffLoginLink: "Staff Login Link",
    staffLoginDesc: "Independent login page for team members.",
    copyStaffLink: "Copy Staff Link",
    staffLinkCopied: "Staff login link copied!",

    // Login
    premiumAccess: 'Premium Terminal Access',
    securityKey: 'Security Key',
    enterDashboard: 'Enter Dashboard',
    authorizedUse: 'Authorized Use Only',
    contactAdmin: 'Contact System Admin',

    // Loyalty & Billing
    loyaltyProgram: 'Loyalty Program',
    loyaltyProgramDesc: 'Reward customers with points on every purchase',
    pointsPerCurrencyHelp: 'e.g., 1 = earn 1 point per $1 spent',
    minPointsRedeem: 'Minimum Points to Redeem',
    minPointsRedeemHelp: 'Customers need at least this many points before they can redeem',
    howItWorks: 'How it works',
    loyaltyExplanation: 'Customers earn points on every purchase. They can redeem them at checkout based on these settings.',
    reportingPeriod: 'Reporting Period',
    billingCycleDescription: 'Your financial reports and dashboard will use this day as the start of each business month.',
    invalidLogin: 'Invalid username or password',
    stayLoggedIn: 'Stay logged in for 30 days',
    noActivePromoCodes: "No active promo codes.",
    monthlySalesCycle: "Monthly Sales Cycle",
    configureBusinessMonth: "Configure when your business month starts.",
    autoResetEnabled: "Auto-Reset Enabled:",
    autoResetDescription: "On day {day} of every month, your dashboard and reports will automatically refresh to show the new period's data. Previous sales are safely stored in history.",
    globalSettingsAdminOnly: "Global shop settings are managed by administrators.",
    databaseDiagnostics: "Database Diagnostics",
    verifyCloudConnection: "Verify your global cloud connection.",
    status: "Status",
    errorMessage: "Error Message",
    configurationCheck: "Configuration Check",
    premiumGrooming: "Premium Business Management",
    pro: "Pro:",
    client: "Client:",
    offlineModeActive: "Offline Mode Active",
    offlineModeMessage: "You can still make bills, but they will not sync to the cloud until connection is restored.",
    searchReturnMessage: "Search for a sale ID or client name to find transactions eligible for return.",
    clientStaffInfo: "Client: {client} • Staff: {staff}",
    noSalesFound: "No sales found matching",
    enterSaleIdRefund: "Enter a Sale ID to begin refund process.",
    itemsToReturn: "Items to Return",
    selectItemsRefund: "Select items for partial or full refund",
    refundTotal: "Refund Total",
    held: "Held",
    selectToResume: "Select to resume",
    loyaltyPointsUsed: "Loyalty Points Used",
    loyaltyPointsAvailable: "Loyalty Points Available",
    cashAmount: "Cash Amount",
    cardAmount: "Card Amount",
    cancelSplit: "Cancel Split",
    quickDiscount: "Quick Discount",
    itemNotInCatalog: "Item not in catalog.",
    alignBarcode: "Align barcode horizontally",
    discardHeldBill: "Discard Held Bill",
    confirmDiscardHeldBill: "Are you sure you want to discard this held bill?",
    commandCenter: "Command Center",
    deleteProfessional: "Delete Professional",
    permanentlyRemoveTeamMember: "Permanently remove this team member?",
    somethingWentWrong: "Something went wrong",
    unexpectedError: "We encountered an unexpected error loading this section.",
    error: "Error",

    // Missing keys (present in Urdu but were absent in English)
    startingCash: "Starting Cash",
    endingCash: "Ending Cash",
    actualCash: "Actual Cash",
    discrepancy: "Discrepancy",
    openDrawer: "Open Drawer",
    closeDrawer: "Close Drawer",
    loyaltyEnabled: "Enable Loyalty Program",
    pointsPerCurrency: "Points Per Currency Unit",
    minPointsToRedeem: "Minimum Points to Redeem",
    customerPreferences: "Customer Preferences",
    stockLogs: "Stock Logs",
    adjustment: "Adjustment",
    restock: "Restock",
    damage: "Damage",
    return: "Return",
    profitAndLoss: "Profit & Loss",
    taxSummary: "Tax Summary",
    exportCSV: "Export CSV",
    supplierName: "Supplier Name",
    contactPerson: "Contact Person",
    address: "Address",
    phone: "Phone",
    stock: "Stock",
    exportPDF: "Export PDF",
    totalStockValue: "Total Stock Value",
    netProfitMargin: "Net Profit Margin",
    costOfGoods: "Cost of Goods",
    grossProfit: "Gross Profit",
    noMatchingEntries: "Try changing your search or add a new entry.",
    confirmDeletion: "Confirm Deletion",
    permanentlyDeleteEntry: "Are you sure you want to permanently delete this entry?",
    noMatchingClients: "No matching clients found.",
    last: "Last",
    noRecordedTransactions: "No recorded transactions.",
    deleteClient: "Delete Client",
    permanentlyDeleteClient: "Are you sure you want to permanently delete this client profile?",
    transactionReceipt: "Transaction Receipt",
    overview: "Overview",
    transactions: "Transactions",
    taxableRevenue: "Taxable Revenue",
    taxCollected: "Tax Collected",
    taxLiability: "Tax Liability",
    basedOn: "Based on",
    deleteSelected: "Delete Selected",
    time: "Time",
    action: "Action",
    view: "View",
    save: "Save",
    delete: "Delete",
    remove: "Remove",
    afterExpenseShare: "After Expense Share",
    drawerClosedMessage: "Cash drawer is currently closed. Enter starting cash to open it.",
    lastClosed: "Last Closed",
    expectedCash: "Expected Cash",
    cashSales: "Cash Sales",
    cardSales: "Card Sales",
    splitSales: "Split Sales",
    totalSessionRevenue: "Total Session Revenue",
    deleteData: "Delete Data",
    confirmDeleteTransactions: "Are you sure you want to delete these transactions? This action cannot be undone.",
    selectMonth: "Select Month",
    selectYear: "Select Year",
    database: "Database",
    online: "Online",
    offline: "Offline",
    shopManagerAdmin: "Shop Manager Admin",
    thankYouChoosingUs: "Thank you for choosing us!",
    hair: "Hair",
    beard: "Beard",
    shave: "Shave",
    face: "Face",
    staffAvailability: "Working Hours",
    closed: "Off Duty",
  },
  ur: {
    // Navigation
    dashboard: 'ڈیش بورڈ',
    pos: 'پوائنٹ آف سیل',
    catalog: 'کیٹلاگ',
    customers: 'صارفین',
    staff: 'عملے کا انتظام',
    finance: 'مالیات',
    settings: 'ترتیبات',
    appointments: 'تقرریاں',
    logout: 'لاگ آؤٹ',
    shopStatus: 'دکان کی حیثیت',
    terminalLive: 'ٹرمینل لائیو',
    transactionHistory: 'لین دین کی تاریخ',

    // Dashboard
    performanceInsights: 'کارکردگی کا جائزہ',
    welcomeBack: 'خوش آمدید! آپ کی دکان میں کیا ہو رہا ہے۔',
    revenue: 'آمدنی',
    expenses: 'اخراجات',
    netProfit: 'خالص منافع',
    avgTicket: 'اوسط ٹکٹ',
    revenueTrends: 'آمدنی کا رجحان',
    recentTransactions: 'حالیہ لین دین',
    waitingForSale: 'پہلی فروخت کا انتظار...',
    last7Days: 'پچھلے 7 دن',
    today: 'آج',
    week: 'اس ہفتے',
    month: 'اس مہینے',
    all: 'تمام وقت',
    custom: 'حسب ضرورت حد',
    lowStockAlerts: 'کم اسٹاک الرٹس',
    itemsRestock: 'اشیاء کو دوبارہ ذخیرہ کرنے کی ضرورت ہے',
    restockNow: 'ابھی دوبارہ ذخیرہ کریں',
    inventoryValue: 'انوینٹری کی قیمت',
    payroll: 'پے رول',
    remainingBalance: 'باقی ماندہ رقم',
    topPerformers: 'بہترین کارکردگی دکھانے والے',
    topServices: 'بہترین خدمات',
    topProducts: 'بہترین مصنوعات',
    staffLeaderboard: 'عملے کا لیڈر بورڈ',
    expenseBreakdown: 'اخراجات کی تفصیل',
    alertQty: 'الرٹ مقدار',
    noRecords: 'کوئی ریکارڈ نہیں ملا۔',

    // POS
    services: 'خدمات',
    products: 'مصنوعات',
    searchCatalog: 'کیٹلاگ تلاش کریں...',
    scanBarcode: 'بارکوڈ اسکین کریں',
    stopScanning: 'اسکیننگ روکیں',
    cart: 'ٹوکری',
    emptyCart: 'خالی ٹوکری',
    subtotal: 'ذیلی کل',
    discount: 'رعایت',
    tax: 'ٹیکس',
    total: 'کل',
    cash: 'نقد',
    card: 'کارڈ',
    holdBill: 'بل روکیں',
    heldBills: 'روکے گئے بل',
    resume: 'بحال کریں',
    saleSuccess: 'فروخت کامیاب',
    orderCompleted: 'آرڈر مکمل',
    shareReceipt: 'رسید شیئر کریں',
    downloadPdf: 'پی ڈی ایف ڈاؤن لوڈ',
    startNewBill: 'نیا بل شروع کریں',
    chooseProfessional: 'پیشہ ور منتخب کریں...',
    walkInClient: 'واک ان کلائنٹ',
    quickAddClient: 'فوری کلائنٹ شامل کریں',
    addSelectClient: 'شامل اور منتخب کریں',
    name: 'نام (انگریزی)',
    nameUr: 'نام (اردو)',
    mobile: 'موبائل',
    email: 'ای میل',
    optional: 'اختیاری',

    // Finance
    shopPerformance: 'دکان کی کارکردگی',
    commissionReport: 'کمیشن رپورٹ',
    payrollReport: 'تاریخ کی حد کے لحاظ سے پے رول رپورٹ تیار کریں۔',
    newExpense: 'نیا خرچ',
    history: 'تاریخچہ',
    periodRevenue: 'مدت کی آمدنی',
    totalPayout: 'کل ادائیگی',
    professional: 'پیشہ ور',
    salesCount: 'فروخت کی تعداد',
    totalSales: 'کل فروخت',
    payout: 'ادائیگی',
    rate: 'شرح',
    category: 'زمرہ',
    amount: 'رقم',
    details: 'تفصیلات',
    addExpense: 'خرچ شامل کریں',
    smartInsights: 'اسمارٹ AI بصیرت',
    generateAdvice: 'مشورہ حاصل کریں',
    analyzing: 'تجزیہ ہو رہا ہے...',
    aiPrompt: 'ذاتی کاروباری تجزیے کے لیے "مشورہ حاصل کریں" پر ٹیپ کریں۔',
    noSalesPeriod: 'اس مدت میں کوئی فروخت نہیں ہوئی۔',
    noteDetails: 'کوئی تفصیلات نوٹ کریں...',
    exportReports: 'رپورٹ برآمد کریں',
    downloadDaily: 'روزانہ ڈاؤن لوڈ کریں',
    downloadWeekly: 'ہفتہ وار ڈاؤن لوڈ کریں',
    downloadMonthly: 'ماہانہ ڈاؤن لوڈ کریں',

    // Customers
    directory: 'ڈائریکٹری',
    clientProfiles: 'کلائنٹ پروفائلز اور تاریخ۔',
    addClient: 'کلائنٹ شامل کریں',
    searchClients: 'کلائنٹ تلاش کریں...',
    visits: 'دورے',
    lifetime: 'لائف ٹائم',
    lastSeen: 'آخری بار دیکھا',
    stylePreferences: 'اسٹائل کی ترجیحات',
    noNotes: 'فائل پر کوئی نوٹس نہیں ہیں۔',
    date: 'تاریخ',
    items: 'اشیاء',
    registerClient: 'کلائنٹ رجسٹر کریں',
    createProfile: 'پروفائل بنائیں',
    pickClient: 'گرومنگ کی تاریخ کا جائزہ لینے کے لیے کلائنٹ کا انتخاب کریں۔',
    member: 'ممبر',
    vip: 'وی آئی پی',

    // Staff
    teamHub: 'ٹیم ہب',
    manageAccess: 'رسائی اور کمائی کا انتظام کریں۔',
    addStaff: 'عملہ شامل کریں',
    loginId: 'لاگ ان آئی ڈی',
    role: 'عہدہ',
    commission: 'کمیسیون',
    actions: 'اقدامات',
    editProfessional: 'پیشہ ور میں ترمیم کریں',
    addToTeam: 'ٹیم میں شامل کریں',
    fullName: 'پورا نام',
    username: 'صارف کا نام',
    password: 'پاس ورڈ',
    employee: 'ملازم',
    admin: 'ایڈمن',
    saveProfessional: 'پیشہ ور کو محفوظ کریں',
    updateProfessional: 'پیشہ ور کو اپ ڈیٹ کریں',

    // Inventory
    shopCatalog: 'دکان کیٹلاگ',
    updatePrices: 'قیمتیں اور اسٹاک اپ ڈیٹ کریں۔',
    newService: 'نئی سروس',
    newProduct: 'نئی پروڈکٹ',
    inventory: 'انوینٹری',
    itemDetails: 'آئٹم کی تفصیلات',
    stockStatus: 'اسٹاک کی حیثیت',
    price: 'قیمت',
    editEntry: 'اندراج میں ترمیم کریں',
    newEntry: 'نیا اندراج',
    labelName: 'لیبل کا نام',
    barcode: 'بارکوڈ',
    mins: 'منٹ',
    cost: 'لاگت',
    initialStock: 'ابتدائی اسٹاک',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    unitsLeft: 'یونٹس باقی',
    session: 'سیشن',

    // Settings
    fineTune: 'اپنی دکان اور مواصلات کو بہتر بنائیں۔',
    shopBranding: 'شاپ برانڈنگ اور لوکلائزیشن',
    terminalIdentity: 'ٹرمینل شناخت',
    language: 'زبان',
    countryCode: 'پہلے سے طے شدہ ملک کا کوڈ',
    preferredCurrency: 'پسندیدہ کرنسی',
    taxCalculation: 'ٹیکس کا حساب کتاب',
    taxRate: 'ٹیکس کی شرح (%)',
    receiptFooter: 'رسید فوٹر',
    whatsAppSummaries: 'واٹس ایپ خلاصے',
    enableWhatsApp: 'واٹس ایپ کے ذریعے ڈیجیٹل رسیدیں فعال کریں۔',
    businessMobile: 'کاروباری موبائل نمبر',
    resetChanges: 'تبدیلیاں دوبارہ ترتیب دیں',
    saveSettings: 'تمام ترتیبات محفوظ کریں',
    excluded: 'شامل نہیں',
    included: 'شامل',
    customSymbol: 'حسب ضرورت علامت...',
    billingCycle: 'بلنگ سائیکل',
    billingDay: 'مہینے کا آغاز',
    dangerZone: 'خطرہ زون',
    resetSales: 'فروخت کی تاریخ کو دوبارہ ترتیب دیں۔',
    resetSalesDesc: 'فروخت کی تمام تاریخ کو مستقل طور پر حذف کریں۔ اسے کالعدم نہیں کیا جا سکتا۔',
    confirmReset: 'کیا آپ واقعی فروخت کے تمام ریکارڈ حذف کرنا چاہتے ہیں؟',
    promoCodes: 'پرومو کوڈز اور کوپن',
    addPromo: 'پرومو کوڈ شامل کریں',
    code: 'کوڈ',
    discountType: 'ڈسکاؤنٹ کی قسم',
    value: 'قیمت',
    description: 'تفصیل',
    fixed: 'مقررہ رقم',
    percentage: 'فیصد (%)',
    deductExpenses: 'کمیشن سے دکان کے اخراجات منہا کریں',
    deductExpensesDesc: 'اگر فعال ہو تو، عملے کے کمیشن کا حساب لگانے سے پہلے کل دکان کے اخراجات آمدنی سے منہا کر دیے جائیں گے۔',
    advancePayments: 'پیشگی ادائیگیاں',
    addAdvance: 'پیشگی ادائیگی شامل کریں',
    payoutSummary: 'ادائیگی کا خلاصہ',
    netCommission: 'خالص کمیشن',
    totalAdvances: 'کل پیشگی',
    finalPayout: 'حتمی ادائیگی',

    // New translations
    searchRefund: "رقم کی واپسی کے لیے سیل آئی ڈی تلاش کریں...",
    splitPayment: "تقسیم شدہ ادائیگی",
    holdResume: "روکیں/بحال کریں",
    refunds: "رقم کی واپسی",
    loyaltyPoints: "وفاداری پوائنٹس",
    suppliers: "سپلائرز",
    onlineBooking: "آن لائن بکنگ",
    bookingSlug: "بکنگ لنک سلگ",
    enableBooking: "عوامی بکنگ صفحہ فعال کریں",
    copyBookingLink: "بکنگ لنک کاپی کریں",
    bookingLinkCopied: "بکنگ لنک کاپی ہو گیا!",
    approvalQueue: "منظوری کی قطار",
    confirmBooking: "بکنگ کی تصدیق کریں",
    declineBooking: "بکنگ مسترد کریں",
    bookingStatusUnconfirmed: "منظوری کا انتظار ہے",
    bookingStatusConfirmed: "تصدیق شدہ",
    cashDrawer: "کیش دراز",
    staffLoginLink: "عملے کا لاگ ان لنک",
    staffLoginDesc: "ٹیم کے اراکین کے لیے آزاد لاگ ان صفحہ۔",
    copyStaffLink: "لنک کاپی کریں",
    staffLinkCopied: "عملے کا لاگ ان لنک کاپی ہو گیا!",
    startingCash: "ابتدائی نقد",
    endingCash: "اختتامی نقد",
    actualCash: "اصل نقد",
    discrepancy: "فرق",
    openDrawer: "دراز کھولیں",
    closeDrawer: "دراز بند کریں",
    loyaltyEnabled: "وفاداری پروگرام فعال کریں",
    pointsPerCurrency: "فی کرنسی یونٹ پوائنٹس",
    minPointsToRedeem: "ریڈیم کرنے کے لیے کم از کم پوائنٹس",
    customerPreferences: "صارف کی ترجیحات",
    stockLogs: "اسٹاک لاگز",
    adjustment: "ایڈجسٹمنٹ",
    restock: "دوبارہ اسٹاک کریں",
    damage: "نقصان",
    return: "واپسی",
    profitAndLoss: "نفع و نقصان",
    taxSummary: "ٹیکس کا خلاصہ",
    exportCSV: "CSV میں برآمد کریں",
    supplierName: "سپلائر کا نام",
    contactPerson: "رابطہ شخص",
    address: "پتہ",
    phone: "فون",
    stock: "اسٹاک",
    exportPDF: "PDF میں برآمد کریں",
    totalStockValue: "کل اسٹاک کی قیمت",
    netProfitMargin: "خالص منافع کا مارجن",
    costOfGoods: "اشیاء کی لاگت",
    grossProfit: "مجموعی منافع",
    noMatchingEntries: "اپنی تلاش کو تبدیل کرنے کی کوشش کریں یا نیا اندراج شامل کریں۔",
    confirmDeletion: "حذف کرنے کی تصدیق کریں",
    permanentlyDeleteEntry: "کیا آپ واقعی اس اندراج کو مستقل طور پر حذف کرنا چاہتے ہیں؟",
    noMatchingClients: "کوئی مماثل کلائنٹ نہیں ملا۔",
    last: "آخری",
    noRecordedTransactions: "کوئی ریکارڈ شدہ لین دین نہیں ہے۔",
    deleteClient: "کلائنٹ کو حذف کریں",
    permanentlyDeleteClient: "کیا آپ واقعی اس کلائنٹ پروفائل کو مستقل طور پر حذف کرنا چاہتے ہیں؟",
    transactionReceipt: "لین دین کی رسید",
    overview: "جائزہ",
    transactions: "لین دین",
    taxableRevenue: "قابل ٹیکس آمدنی",
    taxCollected: "وصول شدہ ٹیکس",
    taxLiability: "ٹیکس کی ذمہ داری",
    basedOn: "کی بنیاد پر",
    deleteSelected: "منتخب کردہ کو حذف کریں",
    time: "وقت",
    action: "عمل",
    view: "دیکھیں",
    save: "محفوظ کریں",
    delete: "حذف کریں",
    remove: "ہٹائیں",
    afterExpenseShare: "اخراجات کے اشتراک کے بعد",
    drawerClosedMessage: "کیش دراز فی الحال بند ہے۔ اسے کھولنے کے لیے ابتدائی نقد درج کریں۔",
    lastClosed: "آخری بار بند ہوا",
    expectedCash: "متوقع نقد",
    cashSales: "نقد فروخت",
    cardSales: "کارڈ فروخت",
    splitSales: "تقسیم فروخت",
    totalSessionRevenue: "کل سیشن کی آمدنی",
    deleteData: "ڈیٹا حذف کریں",
    confirmDeleteTransactions: "کیا آپ واقعی ان لین دین کو حذف کرنا چاہتے ہیں؟ یہ عمل کالعدم نہیں کیا جا سکتا۔",
    selectMonth: "مہینہ منتخب کریں",
    selectYear: "سال منتخب کریں",
    database: "ڈیٹا بیس",
    online: "آن لائن",
    offline: "آف لائن",
    shopManagerAdmin: "شاپ مینیجر ایڈمن",
    thankYouChoosingUs: "ہمیں منتخب کرنے کا شکریہ!",
    hair: "بال",
    beard: "داڑھی",
    shave: "شیو",
    face: "چہرہ",

    // Login
    premiumAccess: 'پریمیم ٹرمینل تک رسائی',
    securityKey: 'سیکیورٹی کلید',
    enterDashboard: 'ڈیش بورڈ میں داخل ہوں',
    authorizedUse: 'صرف مجاز استعمال',
    contactAdmin: 'سسٹم ایڈمن سے رابطہ کریں',

    // Loyalty & Billing
    loyaltyProgram: 'لائلٹی پروگرام',
    loyaltyProgramDesc: 'ہر خریداری پر صارفین کو پوائنٹس سے نوازیں',
    pointsPerCurrencyHelp: 'مثال کے طور پر، 1 = $1 خرچ پر 1 پوائنٹ کمائیں',
    minPointsRedeem: 'ریڈیم کرنے کے لیے کم از کم پوائنٹس',
    minPointsRedeemHelp: 'صارفین کو ریڈیم کرنے سے پہلے کم از کم اتنے پوائنٹس کی ضرورت ہوتی ہے',
    howItWorks: 'یہ کیسے کام کرتا ہے',
    loyaltyExplanation: 'صارفین ہر خریداری پر پوائنٹس کماتے ہیں۔ وہ چیک آؤٹ کے وقت ان ترتیبات کی بنیاد پر انہیں ریڈیم کر سکتے ہیں۔',
    reportingPeriod: 'رپورٹنگ کی مدت',
    billingCycleDescription: 'آپ کی مالیاتی رپورٹس اور ڈیش بورڈ ہر کاروباری مہینے کے آغاز کے طور پر اس دن کا استعمال کریں گے۔',
    invalidLogin: 'غلط صارف نام یا پاس ورڈ',
    stayLoggedIn: '30 دن تک لاگ ان رہیں',
    noActivePromoCodes: "کوئی فعال پرومو کوڈ نہیں ہے۔",
    monthlySalesCycle: "ماہانہ سیلز سائیکل",
    configureBusinessMonth: "ترتیب دیں کہ آپ کا کاروباری مہینہ کب شروع ہوتا ہے۔",
    autoResetEnabled: "آٹو ری سیٹ فعال:",
    autoResetDescription: "ہر مہینے کے دن {day} پر، آپ کا ڈیش بورڈ اور رپورٹس خود بخود نئی مدت کا ڈیٹا دکھانے کے لیے ریفریش ہو جائیں گی۔ پچھلی سیلز محفوظ طریقے سے ہسٹری میں محفوظ ہیں۔",
    globalSettingsAdminOnly: "عالمی دکان کی ترتیبات کا انتظام منتظمین کرتے ہیں۔",
    databaseDiagnostics: "ڈیٹا بیس کی تشخیص",
    verifyCloudConnection: "اپنے عالمی کلاؤڈ کنکشن کی تصدیق کریں۔",
    status: "حیثیت",
    errorMessage: "غلطی کا پیغام",
    configurationCheck: "ترتیب کی جانچ",
    premiumGrooming: "پریمیم کاروبار مینجمنٹ",
    pro: "پرو:",
    client: "کلائنٹ:",
    offlineModeActive: "آف لائن موڈ فعال",
    offlineModeMessage: "آپ اب بھی بل بنا سکتے ہیں، لیکن کنکشن بحال ہونے تک وہ کلاؤڈ سے مطابقت پذیر نہیں ہوں گے۔",
    searchReturnMessage: "واپسی کے اہل لین دین تلاش کرنے کے لیے سیل آئی ڈی یا کلائنٹ کا نام تلاش کریں۔",
    clientStaffInfo: "کلائنٹ: {client} • عملہ: {staff}",
    noSalesFound: "کوئی سیلز نہیں ملیں جو مماثل ہوں",
    enterSaleIdRefund: "رقم کی واپسی کا عمل شروع کرنے کے لیے سیل آئی ڈی درج کریں۔",
    itemsToReturn: "واپس کرنے کے لیے اشیاء",
    selectItemsRefund: "جزوی یا مکمل رقم کی واپسی کے لیے اشیاء منتخب کریں",
    refundTotal: "رقم کی واپسی کا کل",
    held: "روکا ہوا",
    selectToResume: "دوبارہ شروع کرنے کے لیے منتخب کریں",
    loyaltyPointsUsed: "استعمال شدہ لائلٹی پوائنٹس",
    loyaltyPointsAvailable: "دستیاب لائلٹی پوائنٹس",
    cashAmount: "نقد رقم",
    cardAmount: "کارڈ کی رقم",
    cancelSplit: "تقسیم منسوخ کریں",
    quickDiscount: "فوری رعایت",
    itemNotInCatalog: "آئٹم کیٹلاگ میں نہیں ہے۔",
    alignBarcode: "بارکوڈ کو افقی طور پر سیدھ میں رکھیں",
    discardHeldBill: "روکا ہوا بل ضائع کریں",
    confirmDiscardHeldBill: "کیا آپ واقعی اس روکے ہوئے بل کو ضائع کرنا چاہتے ہیں؟",
    commandCenter: "کمانڈ سینٹر",
    deleteProfessional: "پیشہ ور کو حذف کریں",
    permanentlyRemoveTeamMember: "اس ٹیم ممبر کو مستقل طور پر ہٹا دیں؟",
    somethingWentWrong: "کچھ غلط ہو گیا",
    unexpectedError: "اس حصے کو لوڈ کرتے وقت ہمیں ایک غیر متوقع خرابی کا سامنا کرنا پڑا۔",
    error: "خرابی",
    staffAvailability: "کام کے اوقات",
    closed: "آف ڈیوٹی",
  }
};

export const INITIAL_SERVICES: Service[] = [
  { id: 's1', name: 'Classic Haircut', nameUr: 'کلاسک ہیئر کٹ', price: 35, duration: 30, category: 'Hair' },
  { id: 's2', name: 'Skin Fade', nameUr: 'اسکن فیڈ', price: 45, duration: 45, category: 'Hair' },
  { id: 's3', name: 'Beard Trim', nameUr: 'داڑھی کی تراش خراش', price: 20, duration: 20, category: 'Beard' },
  { id: 's4', name: 'Luxury Shave', nameUr: 'لگژری شیو', price: 50, duration: 60, category: 'Shave' },
  { id: 's5', name: 'Kid\'s Cut', nameUr: 'بچوں کی کٹنگ', price: 25, duration: 30, category: 'Hair' },
  { id: 's6', name: 'Head Shave', nameUr: 'سر منڈوانا', price: 30, duration: 30, category: 'Hair' },
];

export const INITIAL_PRODUCTS: Product[] = [
  { id: 'p1', name: 'Pomade Matte', nameUr: 'پومیڈ میٹ', price: 18, cost: 8, stock: 24, barcode: '123456789012', lowStockThreshold: 15 },
  { id: 'p2', name: 'Beard Oil', nameUr: 'داڑھی کا تیل', price: 22, cost: 10, stock: 15, barcode: '098765432109', lowStockThreshold: 15 },
  { id: 'p3', name: 'Aftershave Balm', nameUr: 'آفٹر شیو بام', price: 25, cost: 12, stock: 10, barcode: '112233445566', lowStockThreshold: 15 },
  { id: 'p4', name: 'Texture Spray', nameUr: 'ٹیکسچر سپرے', price: 20, cost: 9, stock: 8, barcode: '665544332211', lowStockThreshold: 15 },
];

export const INITIAL_STAFF: Staff[] = [
  { id: 'st1', name: 'Admin User', role: 'admin', commission: 0, username: '1234', password: '1234', isFallback: true },
  { id: 'st2', name: 'Alex Rivers', role: 'employee', commission: 40, username: 'alex', password: 'password123', isFallback: true },
];

export const INITIAL_EXPENSES: Expense[] = [
  { id: 'e1', date: '2024-05-01', category: 'Rent', amount: 2000, description: 'Monthly Shop Rent' },
  { id: 'e2', date: '2024-05-02', category: 'Utilities', amount: 350, description: 'Electricity & Water' },
  { id: 'e3', date: '2024-05-05', category: 'Supplies', amount: 150, description: 'Towels & Cleaning' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'John Smith', phone: '555-0101', email: 'john@example.com', notes: 'Likes a low taper fade.', createdAt: '2024-01-15', loyaltyPoints: 150 },
  { id: 'c2', name: 'Marcus Brown', phone: '555-0102', email: 'marcus@example.com', notes: 'Grows beard long.', createdAt: '2024-02-20', loyaltyPoints: 85 },
];
