
import { Service, Product, Staff, Expense, Customer, DiscountCode, ShopSettings, Language } from './types';

export const CURRENCY_OPTIONS = [
  { label: 'US Dollar ($)', symbol: '$' },
  { label: 'Euro (€)', symbol: '€' },
  { label: 'British Pound (£)', symbol: '£' },
  { label: 'Pakistani Rupee (Rs.)', symbol: 'Rs.' },
  { label: 'Indian Rupee (₹)', symbol: '₹' },
  { label: 'UAE Dirham (د.إ)', symbol: 'د.إ' },
  { label: 'Saudi Riyal (ر.س)', symbol: 'ر.س' },
  { label: 'Canadian Dollar (C$)', symbol: 'C$' },
  { label: 'Australian Dollar (A$)', symbol: 'A$' },
];

export const COUNTRY_CODES = [
  { code: '+1', label: 'US/Canada (+1)' },
  { code: '+44', label: 'UK (+44)' },
  { code: '+92', label: 'Pakistan (+92)' },
  { code: '+91', label: 'India (+91)' },
  { code: '+971', label: 'UAE (+971)' },
  { code: '+966', label: 'Saudi Arabia (+966)' },
  { code: '+61', label: 'Australia (+61)' },
  { code: '+49', label: 'Germany (+49)' },
  { code: '+33', label: 'France (+33)' },
  { code: '+90', label: 'Turkey (+90)' },
  { code: '+20', label: 'Egypt (+20)' },
];

export const INITIAL_DISCOUNT_CODES: DiscountCode[] = [
  { code: 'WELCOME10', type: 'percentage', value: 10, description: '10% off for new customers' },
  { code: 'VIP20', type: 'percentage', value: 20, description: '20% off for VIP members' },
  { code: 'SAVE5', type: 'fixed', value: 5, description: '$5 off total' },
];

export const DEFAULT_SETTINGS: ShopSettings = {
  shopName: 'My Business',
  currency: '$',
  language: 'en',
  countryCode: '+1',
  whatsappEnabled: true,
  whatsappNumber: '',
  receiptFooter: 'Thank you for choosing us!',
  taxRate: 8,
  taxType: 'excluded',
  billingCycleDay: 1,
  promoCodes: INITIAL_DISCOUNT_CODES,
  deductExpensesFromCommission: false,
  loyaltyEnabled: true,
  pointsPerCurrency: 1,
  pointRedemptionValue: 1,
  minPointsToRedeem: 100,
  bookingEnabled: false,
  bookingSlug: ''
};

export const TRANSLATIONS = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    pos: 'POS Terminal',
    catalog: 'Catalog',
    customers: 'Customers',
    staff: 'Staff Management',
    finance: 'Finances',
    settings: 'Settings',
    appointments: 'Appointments',
    logout: 'Logout',
    shopStatus: 'Shop Status',
    terminalLive: 'Terminal Live',
    transactionHistory: 'Transaction History',
    
    // Dashboard
    performanceInsights: 'Performance Insights',
    welcomeBack: "Welcome back! Here's what's happening in your shop.",
    revenue: 'Revenue',
    expenses: 'Expenses',
    netProfit: 'Net Profit',
    avgTicket: 'Avg Ticket',
    revenueTrends: 'Revenue Trends',
    recentTransactions: 'Recent Transactions',
    waitingForSale: 'Waiting for first sale...',
    last7Days: 'Last 7 Days',
    today: 'Today',
    week: 'This Week',
    month: 'This Month',
    all: 'All Time',
    custom: 'Custom Range',
    lowStockAlerts: 'Low Stock Alerts',
    itemsRestock: 'items need restocking',
    restockNow: 'Restock Now',
    inventoryValue: 'Inventory Value',
    payroll: 'Payroll',
    remainingBalance: 'Remaining Balance',
    topPerformers: 'Top Performers',
    topServices: 'Top Services',
    topProducts: 'Top Products',
    staffLeaderboard: 'Staff Leaderboard',
    expenseBreakdown: 'Expense Breakdown',
    alertQty: 'Alert Qty',
    noRecords: 'No records found.',

    // POS
    services: 'Services',
    products: 'Products',
    searchCatalog: 'Search catalog...',
    scanBarcode: 'Scan Barcode',
    stopScanning: 'Stop Scanning',
    cart: 'Cart',
    emptyCart: 'Empty Cart',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    cash: 'Cash',
    card: 'Card',
    holdBill: 'Hold Bill',
    heldBills: 'Held Bills',
    resume: 'Resume',
    saleSuccess: 'Sale Success',
    orderCompleted: 'Order completed.',
    shareReceipt: 'Share Receipt',
    downloadPdf: 'Download PDF',
    startNewBill: 'Start New Bill',
    chooseProfessional: 'Choose Professional...',
    walkInClient: 'Walk-in Client',
    quickAddClient: 'Quick Add Client',
    addSelectClient: 'Add & Select Client',
    name: 'Name',
    nameUr: 'Name (Local Language)',
    nameUrPlaceholder: 'Local language name (optional)',
    mobile: 'Mobile',
    email: 'Email',
    optional: 'Optional',

    // Finance
    shopPerformance: 'Shop Performance',
    commissionReport: 'Commission Report',
    payrollReport: 'Generate payroll reports by date range.',
    newExpense: 'New Expense',
    history: 'History',
    periodRevenue: 'Period Revenue',
    totalPayout: 'Total Payout',
    professional: 'Professional',
    salesCount: 'Sales Count',
    totalSales: 'Total Sales',
    payout: 'Payout',
    rate: 'Rate',
    category: 'Category',
    amount: 'Amount',
    details: 'Details',
    addExpense: 'Add Expense',
    smartInsights: 'Smart AI Insights',
    generateAdvice: 'Generate Advice',
    analyzing: 'Analyzing...',
    aiPrompt: 'Tap "Generate Advice" for a personalized business analysis.',
    noSalesPeriod: 'No sales found in this period.',
    noteDetails: 'Note down any details...',
    exportReports: 'Export Reports',
    downloadDaily: 'Download Daily',
    downloadWeekly: 'Download Weekly',
    downloadMonthly: 'Download Monthly',
    autoWhatsapp: 'Auto WhatsApp',
    addSale: 'Add Sale',
    recentSales: 'Recent Sales',

    // Customers
    directory: 'Directory',
    clientProfiles: 'Client profiles and history.',
    addClient: 'Add Client',
    searchClients: 'Search clients...',
    visits: 'Visits',
    lifetime: 'Lifetime',
    lastSeen: 'Last Seen',
    stylePreferences: 'Style Preferences',
    noNotes: 'No notes on file.',
    date: 'Date',
    items: 'Items',
    registerClient: 'Register Client',
    createProfile: 'Create Profile',
    pickClient: 'Pick a client to review their grooming history.',
    member: 'Member',
    vip: 'VIP',

    // Staff
    teamHub: 'Team Hub',
    manageAccess: 'Manage access and earnings.',
    addStaff: 'Add Staff',
    loginId: 'Login ID',
    role: 'Role',
    commission: 'Commission',
    actions: 'Actions',
    editProfessional: 'Edit Professional',
    addToTeam: 'Add to Team',
    fullName: 'Full Name',
    username: 'Username',
    password: 'Password',
    employee: 'Employee',
    admin: 'Admin',
    saveProfessional: 'Save Professional',
    updateProfessional: 'Update Professional',

    // Inventory
    shopCatalog: 'Shop Catalog',
    updatePrices: 'Update prices and stock.',
    newService: 'New Service',
    newProduct: 'New Product',
    inventory: 'Inventory',
    itemDetails: 'Item Details',
    stockStatus: 'Stock Status',
    price: 'Price',
    editEntry: 'Edit Entry',
    newEntry: 'New Entry',
    labelName: 'Label Name',
    barcode: 'Barcode',
    mins: 'Mins',
    cost: 'Cost',
    initialStock: 'Initial Stock',
    saveChanges: 'Save Changes',
    unitsLeft: 'Units left',
    session: 'session',

    // Settings
    fineTune: 'Fine-tune your shop and communications.',
    shopBranding: 'Shop Branding & Localization',
    terminalIdentity: 'Terminal Identity',
    language: 'Language',
    countryCode: 'Default Country Code',
    preferredCurrency: 'Preferred Currency',
    taxCalculation: 'Tax Calculation',
    taxRate: 'Tax Rate (%)',
    receiptFooter: 'Receipt Footer',
    whatsAppSummaries: 'WhatsApp Summaries',
    enableWhatsApp: 'Enable digital receipts via WhatsApp.',
    businessMobile: 'Business Mobile Number',
    resetChanges: 'Reset Changes',
    saveSettings: 'Save All Settings',
    excluded: 'Excluded',
    included: 'Included',
    customSymbol: 'Custom symbol...',
    billingCycle: 'Billing Cycle',
    billingDay: 'Start Day of Month',
    dangerZone: 'Danger Zone',
    resetSales: 'Reset Sales History',
    resetSalesDesc: 'Permanently delete all sales history. This cannot be undone.',
    confirmReset: 'Are you absolutely sure you want to delete all sales records?',
    promoCodes: 'Promo Codes & Coupons',
    addPromo: 'Add Promo Code',
    code: 'Code',
    discountType: 'Discount Type',
    value: 'Value',
    description: 'Description',
    fixed: 'Fixed Amount',
    percentage: 'Percentage (%)',
    deductExpenses: 'Deduct Shop Expenses from Commission',
    deductExpensesDesc: 'If enabled, total shop expenses will be subtracted from revenue before calculating staff commissions.',
    advancePayments: 'Advance Payments',
    addAdvance: 'Add Advance',
    payoutSummary: 'Payout Summary',
    netCommission: 'Net Commission',
    totalAdvances: 'Total Advances',
    finalPayout: 'Final Payout',
    // New translations
    searchRefund: "Search Sale ID for Refund...",
    splitPayment: "Split Payment",
    holdResume: "Hold/Resume",
    refunds: "Refunds",
    loyaltyPoints: "Loyalty Points",
    suppliers: "Suppliers",
    onlineBooking: "Online Booking",
    bookingSlug: "Booking Link Slug",
    enableBooking: "Enable Public Booking Page",
    copyBookingLink: "Copy Booking Link",
    bookingLinkCopied: "Booking link copied!",
    approvalQueue: "Approval Queue",
    confirmBooking: "Confirm Booking",
    declineBooking: "Decline Booking",
    bookingStatusUnconfirmed: "Waiting for Approval",
    bookingStatusConfirmed: "Confirmed",
    cashDrawer: "Cash Drawer",
    staffLoginLink: "Staff Login Link",
    staffLoginDesc: "Independent login page for team members.",
    copyStaffLink: "Copy Staff Link",
    staffLinkCopied: "Staff login link copied!",

    // Login
    premiumAccess: 'Premium Terminal Access',
    securityKey: 'Security Key',
    enterDashboard: 'Enter Dashboard',
    authorizedUse: 'Authorized Use Only',
    contactAdmin: 'Contact System Admin',

    // Loyalty & Billing
    loyaltyProgram: 'Loyalty Program',
    loyaltyProgramDesc: 'Reward customers with points on every purchase',
    pointsPerCurrencyHelp: 'e.g., 1 = earn 1 point per $1 spent',
    minPointsRedeem: 'Minimum Points to Redeem',
    minPointsRedeemHelp: 'Customers need at least this many points before they can redeem',
    pointValue: 'Point Value (Redemption)',
    pointValueHelp: 'e.g., 1 point = $0.01 discount',
    howItWorks: 'How it works',
    loyaltyExplanation: 'Customers earn points on every purchase. They can redeem them at checkout based on these settings.',
    reportingPeriod: 'Reporting Period',
    billingCycleDescription: 'Your financial reports and dashboard will use this day as the start of each business month.',
    invalidLogin: 'Invalid username or password',
    stayLoggedIn: 'Stay logged in for 30 days',
    noActivePromoCodes: "No active promo codes.",
    monthlySalesCycle: "Monthly Sales Cycle",
    configureBusinessMonth: "Configure when your business month starts.",
    autoResetEnabled: "Auto-Reset Enabled:",
    autoResetDescription: "On day {day} of every month, your dashboard and reports will automatically refresh to show the new period's data. Previous sales are safely stored in history.",
    globalSettingsAdminOnly: "Global shop settings are managed by administrators.",
    databaseDiagnostics: "Database Diagnostics",
    verifyCloudConnection: "Verify your global cloud connection.",
    status: "Status",
    errorMessage: "Error Message",
    configurationCheck: "Configuration Check",
    premiumGrooming: "Premium Business Management",
    pro: "Pro:",
    client: "Client:",
    offlineModeActive: "Offline Mode Active",
    offlineModeMessage: "You can still make bills, but they will not sync to the cloud until connection is restored.",
    searchReturnMessage: "Search for a sale ID or client name to find transactions eligible for return.",
    clientStaffInfo: "Client: {client} • Staff: {staff}",
    noSalesFound: "No sales found matching",
    enterSaleIdRefund: "Enter a Sale ID to begin refund process.",
    itemsToReturn: "Items to Return",
    selectItemsRefund: "Select items for partial or full refund",
    refundTotal: "Refund Total",
    held: "Held",
    selectToResume: "Select to resume",
    loyaltyPointsUsed: "Loyalty Points Used",
    loyaltyPointsAvailable: "Loyalty Points Available",
    cashAmount: "Cash Amount",
    cardAmount: "Card Amount",
    cancelSplit: "Cancel Split",
    quickDiscount: "Quick Discount",
    itemNotInCatalog: "Item not in catalog.",
    alignBarcode: "Align barcode horizontally",
    discardHeldBill: "Discard Held Bill",
    confirmDiscardHeldBill: "Are you sure you want to discard this held bill?",
    commandCenter: "Command Center",
    deleteProfessional: "Delete Professional",
    permanentlyRemoveTeamMember: "Permanently remove this team member?",
    somethingWentWrong: "Something went wrong",
    unexpectedError: "We encountered an unexpected error loading this section.",
    error: "Error",

    // Missing keys (present in Urdu but were absent in English)
    startingCash: "Starting Cash",
    endingCash: "Ending Cash",
    actualCash: "Actual Cash",
    discrepancy: "Discrepancy",
    openDrawer: "Open Drawer",
    closeDrawer: "Close Drawer",
    loyaltyEnabled: "Enable Loyalty Program",
    pointsPerCurrency: "Points Per Currency Unit",
    minPointsToRedeem: "Minimum Points to Redeem",
    customerPreferences: "Customer Preferences",
    stockLogs: "Stock Logs",
    newSupplier: "New Supplier",
    addStockLog: "Add Stock Log",
    adjustment: "Adjustment",
    restock: "Restock",
    damage: "Damage",
    return: "Return",
    profitAndLoss: "Profit & Loss",
    taxSummary: "Tax Summary",
    exportCSV: "Export CSV",
    supplierName: "Supplier Name",
    contactPerson: "Contact Person",
    address: "Address",
    phone: "Phone",
    stock: "Stock",
    exportPDF: "Export PDF",
    totalStockValue: "Total Stock Value",
    netProfitMargin: "Net Profit Margin",
    costOfGoods: "Cost of Goods",
    grossProfit: "Gross Profit",
    noMatchingEntries: "Try changing your search or add a new entry.",
    confirmDeletion: "Confirm Deletion",
    permanentlyDeleteEntry: "Are you sure you want to permanently delete this entry?",
    noMatchingClients: "No matching clients found.",
    last: "Last",
    noRecordedTransactions: "No recorded transactions.",
    deleteClient: "Delete Client",
    permanentlyDeleteClient: "Are you sure you want to permanently delete this client profile?",
    transactionReceipt: "Transaction Receipt",
    overview: "Overview",
    transactions: "Transactions",
    taxableRevenue: "Taxable Revenue",
    taxCollected: "Tax Collected",
    taxLiability: "Tax Liability",
    basedOn: "Based on",
    deleteSelected: "Delete Selected",
    time: "Time",
    action: "Action",
    view: "View",
    save: "Save",
    delete: "Delete",
    remove: "Remove",
    afterExpenseShare: "After Expense Share",
    drawerClosedMessage: "Cash drawer is currently closed. Enter starting cash to open it.",
    lastClosed: "Last Closed",
    expectedCash: "Expected Cash",
    cashSales: "Cash Sales",
    cardSales: "Card Sales",
    splitSales: "Split Sales",
    totalSessionRevenue: "Total Session Revenue",
    deleteData: "Delete Data",
    confirmDeleteTransactions: "Are you sure you want to delete these transactions? This action cannot be undone.",
    selectMonth: "Select Month",
    selectYear: "Select Year",
    database: "Database",
    online: "Online",
    offline: "Offline",
    shopManagerAdmin: "Shop Manager Admin",
    thankYouChoosingUs: "Thank you for choosing us!",
    hair: "Hair",
    beard: "Beard",
    shave: "Shave",
    face: "Face",
    staffAvailability: "Working Hours",
    closed: "Off Duty",
    notificationSettings: 'Notification Settings',
    testNotification: 'Test Notification',
    updatePermissions: 'Update Permissions',
    notificationStatus: 'Notification Status',
    notificationGranted: 'Granted',
    notificationDenied: 'Denied',
    notificationDefault: 'Click to request',
    salaryAndTips: 'Salary & Tips',
    baseSalaryLabel: 'Base: ',
    tipsLabel: 'Tips: ',
    markPaid: 'Mark Paid',
    confirmPaid: 'Confirm',
    cancel: 'Cancel',
    paid: 'Paid',
    confirmDelete: 'Confirm Delete',
    tipAmount: 'Tip Amount',
    addTip: 'Add Tip',
    removeTip: 'Remove Tip',
    baseSalary: 'Base Salary',
    monthlyFixedSalary: 'Monthly fixed salary (optional)',
    onlyLettersNumbersHyphens: 'Only letters, numbers, and hyphens allowed',
    startYourShift: 'Start Your Shift.',
    loginToAccess: 'Log in to access the POS terminal, your appointments, and today\'s performance metrics.',
    sessionDetails: 'Session Details',
    autoExpires12h: 'Auto-expires after 12 hours',
    autoLogoutSecurity: 'You\'ll be automatically logged out for security',
    credentialsEncrypted: 'Credentials are encrypted with bcrypt. Contact your manager if locked out.',
    staffSignInTitle: 'Staff Sign In',
    enterShiftCredentials: 'Enter your shift credentials below.',
    sessionExpiresSecurity: 'Session expires automatically after 12 hours for security.',
    verifying: 'Verifying...',
    shopNotFound: 'Shop not found or inactive.',
    staffRecordsNotFound: 'Staff records not found. Please contact your manager.',
    loading: 'Loading...',

  },
  ur: {
    // Navigation
    dashboard: 'ڈیش بورڈ',
    pos: 'پوائنٹ آف سیل',
    catalog: 'کیٹلاگ',
    customers: 'صارفین',
    staff: 'عملے کا انتظام',
    finance: 'مالیات',
    settings: 'ترتیبات',
    appointments: 'تقرریاں',
    logout: 'لاگ آؤٹ',
    shopStatus: 'دکان کی حیثیت',
    terminalLive: 'ٹرمینل لائیو',
    transactionHistory: 'لین دین کی تاریخ',

    // Dashboard
    performanceInsights: 'کارکردگی کا جائزہ',
    welcomeBack: 'خوش آمدید! آپ کی دکان میں کیا ہو رہا ہے۔',
    revenue: 'آمدنی',
    expenses: 'اخراجات',
    netProfit: 'خالص منافع',
    avgTicket: 'اوسط ٹکٹ',
    revenueTrends: 'آمدنی کا رجحان',
    recentTransactions: 'حالیہ لین دین',
    waitingForSale: 'پہلی فروخت کا انتظار...',
    last7Days: 'پچھلے 7 دن',
    today: 'آج',
    week: 'اس ہفتے',
    month: 'اس مہینے',
    all: 'تمام وقت',
    custom: 'حسب ضرورت حد',
    lowStockAlerts: 'کم اسٹاک الرٹس',
    itemsRestock: 'اشیاء کو دوبارہ ذخیرہ کرنے کی ضرورت ہے',
    restockNow: 'ابھی دوبارہ ذخیرہ کریں',
    inventoryValue: 'انوینٹری کی قیمت',
    payroll: 'پے رول',
    remainingBalance: 'باقی ماندہ رقم',
    topPerformers: 'بہترین کارکردگی دکھانے والے',
    topServices: 'بہترین خدمات',
    topProducts: 'بہترین مصنوعات',
    staffLeaderboard: 'عملے کا لیڈر بورڈ',
    expenseBreakdown: 'اخراجات کی تفصیل',
    alertQty: 'الرٹ مقدار',
    noRecords: 'کوئی ریکارڈ نہیں ملا۔',

    // POS
    services: 'خدمات',
    products: 'مصنوعات',
    searchCatalog: 'کیٹلاگ تلاش کریں...',
    scanBarcode: 'بارکوڈ اسکین کریں',
    stopScanning: 'اسکیننگ روکیں',
    cart: 'ٹوکری',
    emptyCart: 'خالی ٹوکری',
    subtotal: 'ذیلی کل',
    discount: 'رعایت',
    tax: 'ٹیکس',
    total: 'کل',
    cash: 'نقد',
    card: 'کارڈ',
    holdBill: 'بل روکیں',
    heldBills: 'روکے گئے بل',
    resume: 'بحال کریں',
    saleSuccess: 'فروخت کامیاب',
    orderCompleted: 'آرڈر مکمل',
    shareReceipt: 'رسید شیئر کریں',
    downloadPdf: 'پی ڈی ایف ڈاؤن لوڈ',
    startNewBill: 'نیا بل شروع کریں',
    chooseProfessional: 'پیشہ ور منتخب کریں...',
    walkInClient: 'واک ان کلائنٹ',
    quickAddClient: 'فوری کلائنٹ شامل کریں',
    addSelectClient: 'شامل اور منتخب کریں',
    name: 'نام (انگریزی)',
    nameUr: 'نام (اردو)',
    nameUrPlaceholder: 'اردو میں نام',
    mobile: 'موبائل',
    email: 'ای میل',
    optional: 'اختیاری',

    // Finance
    shopPerformance: 'دکان کی کارکردگی',
    commissionReport: 'کمیشن رپورٹ',
    payrollReport: 'تاریخ کی حد کے لحاظ سے پے رول رپورٹ تیار کریں۔',
    newExpense: 'نیا خرچ',
    history: 'تاریخچہ',
    periodRevenue: 'مدت کی آمدنی',
    totalPayout: 'کل ادائیگی',
    professional: 'پیشہ ور',
    salesCount: 'فروخت کی تعداد',
    totalSales: 'کل فروخت',
    payout: 'ادائیگی',
    rate: 'شرح',
    category: 'زمرہ',
    amount: 'رقم',
    details: 'تفصیلات',
    addExpense: 'خرچ شامل کریں',
    smartInsights: 'اسمارٹ AI بصیرت',
    generateAdvice: 'مشورہ حاصل کریں',
    analyzing: 'تجزیہ ہو رہا ہے...',
    aiPrompt: 'ذاتی کاروباری تجزیے کے لیے "مشورہ حاصل کریں" پر ٹیپ کریں۔',
    noSalesPeriod: 'اس مدت میں کوئی فروخت نہیں ہوئی۔',
    noteDetails: 'کوئی تفصیلات نوٹ کریں...',
    exportReports: 'رپورٹ برآمد کریں',
    downloadDaily: 'روزانہ ڈاؤن لوڈ کریں',
    downloadWeekly: 'ہفتہ وار ڈاؤن لوڈ کریں',
    downloadMonthly: 'ماہانہ ڈاؤن لوڈ کریں',

    // Customers
    directory: 'ڈائریکٹری',
    clientProfiles: 'کلائنٹ پروفائلز اور تاریخ۔',
    addClient: 'کلائنٹ شامل کریں',
    searchClients: 'کلائنٹ تلاش کریں...',
    visits: 'دورے',
    lifetime: 'لائف ٹائم',
    lastSeen: 'آخری بار دیکھا',
    stylePreferences: 'اسٹائل کی ترجیحات',
    noNotes: 'فائل پر کوئی نوٹس نہیں ہیں۔',
    date: 'تاریخ',
    items: 'اشیاء',
    registerClient: 'کلائنٹ رجسٹر کریں',
    createProfile: 'پروفائل بنائیں',
    pickClient: 'گرومنگ کی تاریخ کا جائزہ لینے کے لیے کلائنٹ کا انتخاب کریں۔',
    member: 'ممبر',
    vip: 'وی آئی پی',

    // Staff
    teamHub: 'ٹیم ہب',
    manageAccess: 'رسائی اور کمائی کا انتظام کریں۔',
    addStaff: 'عملہ شامل کریں',
    loginId: 'لاگ ان آئی ڈی',
    role: 'عہدہ',
    commission: 'کمیسیون',
    actions: 'اقدامات',
    editProfessional: 'پیشہ ور میں ترمیم کریں',
    addToTeam: 'ٹیم میں شامل کریں',
    fullName: 'پورا نام',
    username: 'صارف کا نام',
    password: 'پاس ورڈ',
    employee: 'ملازم',
    admin: 'ایڈمن',
    saveProfessional: 'پیشہ ور کو محفوظ کریں',
    updateProfessional: 'پیشہ ور کو اپ ڈیٹ کریں',

    // Inventory
    shopCatalog: 'دکان کیٹلاگ',
    updatePrices: 'قیمتیں اور اسٹاک اپ ڈیٹ کریں۔',
    newService: 'نئی سروس',
    newProduct: 'نئی پروڈکٹ',
    inventory: 'انوینٹری',
    itemDetails: 'آئٹم کی تفصیلات',
    stockStatus: 'اسٹاک کی حیثیت',
    price: 'قیمت',
    editEntry: 'اندراج میں ترمیم کریں',
    newEntry: 'نیا اندراج',
    labelName: 'لیبل کا نام',
    barcode: 'بارکوڈ',
    mins: 'منٹ',
    cost: 'لاگت',
    initialStock: 'ابتدائی اسٹاک',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    unitsLeft: 'یونٹس باقی',
    session: 'سیشن',

    // Settings
    fineTune: 'اپنی دکان اور مواصلات کو بہتر بنائیں۔',
    shopBranding: 'شاپ برانڈنگ اور لوکلائزیشن',
    terminalIdentity: 'ٹرمینل شناخت',
    language: 'زبان',
    countryCode: 'پہلے سے طے شدہ ملک کا کوڈ',
    preferredCurrency: 'پسندیدہ کرنسی',
    taxCalculation: 'ٹیکس کا حساب کتاب',
    taxRate: 'ٹیکس کی شرح (%)',
    receiptFooter: 'رسید فوٹر',
    whatsAppSummaries: 'واٹس ایپ خلاصے',
    enableWhatsApp: 'واٹس ایپ کے ذریعے ڈیجیٹل رسیدیں فعال کریں۔',
    businessMobile: 'کاروباری موبائل نمبر',
    resetChanges: 'تبدیلیاں دوبارہ ترتیب دیں',
    saveSettings: 'تمام ترتیبات محفوظ کریں',
    excluded: 'شامل نہیں',
    included: 'شامل',
    customSymbol: 'حسب ضرورت علامت...',
    billingCycle: 'بلنگ سائیکل',
    billingDay: 'مہینے کا آغاز',
    dangerZone: 'خطرہ زون',
    resetSales: 'فروخت کی تاریخ کو دوبارہ ترتیب دیں۔',
    resetSalesDesc: 'فروخت کی تمام تاریخ کو مستقل طور پر حذف کریں۔ اسے کالعدم نہیں کیا جا سکتا۔',
    confirmReset: 'کیا آپ واقعی فروخت کے تمام ریکارڈ حذف کرنا چاہتے ہیں؟',
    promoCodes: 'پرومو کوڈز اور کوپن',
    addPromo: 'پرومو کوڈ شامل کریں',
    code: 'کوڈ',
    discountType: 'ڈسکاؤنٹ کی قسم',
    value: 'قیمت',
    description: 'تفصیل',
    fixed: 'مقررہ رقم',
    percentage: 'فیصد (%)',
    deductExpenses: 'کمیشن سے دکان کے اخراجات منہا کریں',
    deductExpensesDesc: 'اگر فعال ہو تو، عملے کے کمیشن کا حساب لگانے سے پہلے کل دکان کے اخراجات آمدنی سے منہا کر دیے جائیں گے۔',
    advancePayments: 'پیشگی ادائیگیاں',
    addAdvance: 'پیشگی ادائیگی شامل کریں',
    payoutSummary: 'ادائیگی کا خلاصہ',
    netCommission: 'خالص کمیشن',
    totalAdvances: 'کل پیشگی',
    finalPayout: 'حتمی ادائیگی',

    // New translations
    searchRefund: "رقم کی واپسی کے لیے سیل آئی ڈی تلاش کریں...",
    splitPayment: "تقسیم شدہ ادائیگی",
    holdResume: "روکیں/بحال کریں",
    refunds: "رقم کی واپسی",
    loyaltyPoints: "وفاداری پوائنٹس",
    suppliers: "سپلائرز",
    onlineBooking: "آن لائن بکنگ",
    bookingSlug: "بکنگ لنک سلگ",
    enableBooking: "عوامی بکنگ صفحہ فعال کریں",
    copyBookingLink: "بکنگ لنک کاپی کریں",
    bookingLinkCopied: "بکنگ لنک کاپی ہو گیا!",
    approvalQueue: "منظوری کی قطار",
    confirmBooking: "بکنگ کی تصدیق کریں",
    declineBooking: "بکنگ مسترد کریں",
    bookingStatusUnconfirmed: "منظوری کا انتظار ہے",
    bookingStatusConfirmed: "تصدیق شدہ",
    cashDrawer: "کیش دراز",
    staffLoginLink: "عملے کا لاگ ان لنک",
    staffLoginDesc: "ٹیم کے اراکین کے لیے آزاد لاگ ان صفحہ۔",
    copyStaffLink: "لنک کاپی کریں",
    staffLinkCopied: "عملے کا لاگ ان لنک کاپی ہو گیا!",
    startingCash: "ابتدائی نقد",
    endingCash: "اختتامی نقد",
    actualCash: "اصل نقد",
    discrepancy: "فرق",
    openDrawer: "دراز کھولیں",
    closeDrawer: "دراز بند کریں",
    loyaltyEnabled: "وفاداری پروگرام فعال کریں",
    pointsPerCurrency: "فی کرنسی یونٹ پوائنٹس",
    minPointsToRedeem: "ریڈیم کرنے کے لیے کم از کم پوائنٹس",
    customerPreferences: "صارف کی ترجیحات",
    stockLogs: "اسٹاک لاگز",
    newSupplier: "نیا سپلائر",
    addStockLog: "نیا اسٹاک لاگ",
    adjustment: "ایڈجسٹمنٹ",
    restock: "دوبارہ اسٹاک کریں",
    damage: "نقصان",
    return: "واپسی",
    profitAndLoss: "نفع و نقصان",
    taxSummary: "ٹیکس کا خلاصہ",
    exportCSV: "CSV میں برآمد کریں",
    supplierName: "سپلائر کا نام",
    contactPerson: "رابطہ شخص",
    address: "پتہ",
    phone: "فون",
    stock: "اسٹاک",
    exportPDF: "PDF میں برآمد کریں",
    totalStockValue: "کل اسٹاک کی قیمت",
    netProfitMargin: "خالص منافع کا مارجن",
    costOfGoods: "اشیاء کی لاگت",
    grossProfit: "مجموعی منافع",
    noMatchingEntries: "اپنی تلاش کو تبدیل کرنے کی کوشش کریں یا نیا اندراج شامل کریں۔",
    confirmDeletion: "حذف کرنے کی تصدیق کریں",
    permanentlyDeleteEntry: "کیا آپ واقعی اس اندراج کو مستقل طور پر حذف کرنا چاہتے ہیں؟",
    noMatchingClients: "کوئی مماثل کلائنٹ نہیں ملا۔",
    last: "آخری",
    noRecordedTransactions: "کوئی ریکارڈ شدہ لین دین نہیں ہے۔",
    deleteClient: "کلائنٹ کو حذف کریں",
    permanentlyDeleteClient: "کیا آپ واقعی اس کلائنٹ پروفائل کو مستقل طور پر حذف کرنا چاہتے ہیں؟",
    transactionReceipt: "لین دین کی رسید",
    overview: "جائزہ",
    transactions: "لین دین",
    taxableRevenue: "قابل ٹیکس آمدنی",
    taxCollected: "وصول شدہ ٹیکس",
    taxLiability: "ٹیکس کی ذمہ داری",
    basedOn: "کی بنیاد پر",
    deleteSelected: "منتخب کردہ کو حذف کریں",
    time: "وقت",
    action: "عمل",
    view: "دیکھیں",
    save: "محفوظ کریں",
    delete: "حذف کریں",
    remove: "ہٹائیں",
    afterExpenseShare: "اخراجات کے اشتراک کے بعد",
    drawerClosedMessage: "کیش دراز فی الحال بند ہے۔ اسے کھولنے کے لیے ابتدائی نقد درج کریں۔",
    lastClosed: "آخری بار بند ہوا",
    expectedCash: "متوقع نقد",
    cashSales: "نقد فروخت",
    cardSales: "کارڈ فروخت",
    splitSales: "تقسیم فروخت",
    totalSessionRevenue: "کل سیشن کی آمدنی",
    deleteData: "ڈیٹا حذف کریں",
    confirmDeleteTransactions: "کیا آپ واقعی ان لین دین کو حذف کرنا چاہتے ہیں؟ یہ عمل کالعدم نہیں کیا جا سکتا۔",
    selectMonth: "مہینہ منتخب کریں",
    selectYear: "سال منتخب کریں",
    database: "ڈیٹا بیس",
    online: "آن لائن",
    offline: "آف لائن",
    shopManagerAdmin: "شاپ مینیجر ایڈمن",
    thankYouChoosingUs: "ہمیں منتخب کرنے کا شکریہ!",
    hair: "بال",
    beard: "داڑھی",
    shave: "شیو",
    face: "چہرہ",
    autoWhatsapp: 'خودکار واٹس ایپ',
    addSale: 'فروخت شامل کریں',
    recentSales: 'حالیہ فروخت',

    // Login
    premiumAccess: 'پریمیم ٹرمینل تک رسائی',
    securityKey: 'سیکیورٹی کلید',
    enterDashboard: 'ڈیش بورڈ میں داخل ہوں',
    authorizedUse: 'صرف مجاز استعمال',
    contactAdmin: 'سسٹم ایڈمن سے رابطہ کریں',

    // Loyalty & Billing
    loyaltyProgram: 'لائلٹی پروگرام',
    loyaltyProgramDesc: 'ہر خریداری پر صارفین کو پوائنٹس سے نوازیں',
    pointsPerCurrencyHelp: 'مثال کے طور پر، 1 = $1 خرچ پر 1 پوائنٹ کمائیں',
    minPointsRedeem: 'ریڈیم کرنے کے لیے کم از کم پوائنٹس',
    minPointsRedeemHelp: 'صارفین کو ریڈیم کرنے سے پہلے کم از کم اتنے پوائنٹس کی ضرورت ہوتی ہے',
    pointValue: 'پوائنٹ کی قیمت (ریڈیمپشن)',
    pointValueHelp: 'مثال کے طور پر، 1 پوائنٹ = 0.01 رعایت',
    howItWorks: 'یہ کیسے کام کرتا ہے',
    loyaltyExplanation: 'صارفین ہر خریداری پر پوائنٹس کماتے ہیں۔ وہ چیک آؤٹ کے وقت ان ترتیبات کی بنیاد پر انہیں ریڈیم کر سکتے ہیں۔',
    reportingPeriod: 'رپورٹنگ کی مدت',
    billingCycleDescription: 'آپ کی مالیاتی رپورٹس اور ڈیش بورڈ ہر کاروباری مہینے کے آغاز کے طور پر اس دن کا استعمال کریں گے۔',
    invalidLogin: 'غلط صارف نام یا پاس ورڈ',
    stayLoggedIn: '30 دن تک لاگ ان رہیں',
    noActivePromoCodes: "کوئی فعال پرومو کوڈ نہیں ہے۔",
    monthlySalesCycle: "ماہانہ سیلز سائیکل",
    configureBusinessMonth: "ترتیب دیں کہ آپ کا کاروباری مہینہ کب شروع ہوتا ہے۔",
    autoResetEnabled: "آٹو ری سیٹ فعال:",
    autoResetDescription: "ہر مہینے کے دن {day} پر، آپ کا ڈیش بورڈ اور رپورٹس خود بخود نئی مدت کا ڈیٹا دکھانے کے لیے ریفریش ہو جائیں گی۔ پچھلی سیلز محفوظ طریقے سے ہسٹری میں محفوظ ہیں۔",
    globalSettingsAdminOnly: "عالمی دکان کی ترتیبات کا انتظام منتظمین کرتے ہیں۔",
    databaseDiagnostics: "ڈیٹا بیس کی تشخیص",
    verifyCloudConnection: "اپنے عالمی کلاؤڈ کنکشن کی تصدیق کریں۔",
    status: "حیثیت",
    errorMessage: "غلطی کا پیغام",
    configurationCheck: "ترتیب کی جانچ",
    premiumGrooming: "پریمیم کاروبار مینجمنٹ",
    pro: "پرو:",
    client: "کلائنٹ:",
    offlineModeActive: "آف لائن موڈ فعال",
    offlineModeMessage: "آپ اب بھی بل بنا سکتے ہیں، لیکن کنکشن بحال ہونے تک وہ کلاؤڈ سے مطابقت پذیر نہیں ہوں گے۔",
    searchReturnMessage: "واپسی کے اہل لین دین تلاش کرنے کے لیے سیل آئی ڈی یا کلائنٹ کا نام تلاش کریں۔",
    clientStaffInfo: "کلائنٹ: {client} • عملہ: {staff}",
    noSalesFound: "کوئی سیلز نہیں ملیں جو مماثل ہوں",
    enterSaleIdRefund: "رقم کی واپسی کا عمل شروع کرنے کے لیے سیل آئی ڈی درج کریں۔",
    itemsToReturn: "واپس کرنے کے لیے اشیاء",
    selectItemsRefund: "جزوی یا مکمل رقم کی واپسی کے لیے اشیاء منتخب کریں",
    refundTotal: "رقم کی واپسی کا کل",
    held: "روکا ہوا",
    selectToResume: "دوبارہ شروع کرنے کے لیے منتخب کریں",
    loyaltyPointsUsed: "استعمال شدہ لائلٹی پوائنٹس",
    loyaltyPointsAvailable: "دستیاب لائلٹی پوائنٹس",
    cashAmount: "نقد رقم",
    cardAmount: "کارڈ کی رقم",
    cancelSplit: "تقسیم منسوخ کریں",
    quickDiscount: "فوری رعایت",
    itemNotInCatalog: "آئٹم کیٹلاگ میں نہیں ہے۔",
    alignBarcode: "بارکوڈ کو افقی طور پر سیدھ میں رکھیں",
    discardHeldBill: "روکا ہوا بل ضائع کریں",
    confirmDiscardHeldBill: "کیا آپ واقعی اس روکے ہوئے بل کو ضائع کرنا چاہتے ہیں؟",
    commandCenter: "کمانڈ سینٹر",
    deleteProfessional: "پیشہ ور کو حذف کریں",
    permanentlyRemoveTeamMember: "اس ٹیم ممبر کو مستقل طور پر ہٹا دیں؟",
    somethingWentWrong: "کچھ غلط ہو گیا",
    unexpectedError: "اس حصے کو لوڈ کرتے وقت ہمیں ایک غیر متوقع خرابی کا سامنا کرنا پڑا۔",
    error: "خرابی",
    staffAvailability: "کام کے اوقات",
    closed: "آف ڈیوٹی",
    notificationSettings: 'نوٹیفیکیشن کی ترتیبات',
    testNotification: 'ٹیسٹ نوٹیفیکیشن',
    updatePermissions: 'اجازتیں اپ ڈیٹ کریں',
    notificationStatus: 'نوٹیفیکیشن کی صورتحال',
    notificationGranted: 'اجازت مل گئی',
    notificationDenied: 'اجازت نہیں ملی',
    notificationDefault: 'درخواست کے لیے کلک کریں',
    salaryAndTips: 'تنخواہ اور ٹپس',
    baseSalaryLabel: 'بنیادی: ',
    tipsLabel: 'ٹپس: ',
    markPaid: 'ادائیگی کریں',
    confirmPaid: 'تصدیق کریں',
    cancel: 'منسوخ کریں',
    paid: 'ادا شدہ',
    confirmDelete: 'حذف کرنے کی تصدیق کریں',
    tipAmount: 'ٹپ کی رقم',
    addTip: 'ٹپ شامل کریں',
    removeTip: 'ٹپ ہٹائیں',
    baseSalary: 'بنیادی تنخواہ',
    monthlyFixedSalary: 'ماہانہ مقررہ تنخواہ (اختیاری)',
    onlyLettersNumbersHyphens: 'صرف حروف، اعداد اور ہائفنز کی اجازت ہے',
    startYourShift: 'اپنی شفٹ شروع کریں۔',
    loginToAccess: 'POS ٹرمینل، تقرریوں، اور کارکردگی تک رسائی حاصل کریں۔',
    sessionDetails: 'سیشن کی تفصیلات',
    autoExpires12h: '12 گھنٹے بعد خود بخود ختم',
    autoLogoutSecurity: 'سیکیورٹی کے لیے آپ خود بخود لاگ آؤٹ ہو جائیں گے',
    credentialsEncrypted: 'اسناد محفوظ ہیں۔ لاک آؤٹ ہونے پر مینیجر سے رابطہ کریں۔',
    staffSignInTitle: 'عملے کا لاگ ان',
    enterShiftCredentials: 'نیچے اپنی شفٹ کی تفصیلات درج کریں۔',
    sessionExpiresSecurity: 'سیکیورٹی کے لیے سیشن 12 گھنٹے بعد ختم ہوتا ہے۔',
    verifying: 'تصدیق کی جا رہی ہے...',
    shopNotFound: 'دکان نہیں ملی یا غیر فعال ہے۔',
    staffRecordsNotFound: 'عملے کا ریکارڈ نہیں ملا۔ مینیجر سے رابطہ کریں۔',
    loading: 'لوڈ ہو رہا ہے...',

  },
  ar: {
    dashboard: 'لوحة القيادة',
    pos: 'نقاط البيع',
    catalog: 'الكتالوج',
    customers: 'العملاء',
    staff: 'إدارة الموظفين',
    finance: 'المالية',
    settings: 'الإعدادات',
    appointments: 'المواعيد',
    logout: 'تسجيل الخروج',
    shopStatus: 'حالة المتجر',
    terminalLive: 'المحطة نشطة',
    transactionHistory: 'سجل المعاملات',
    performanceInsights: 'رؤى الأداء',
    welcomeBack: 'مرحباً بعودتك! إليك ما يحدث في متجرك.',
    revenue: 'الإيرادات',
    expenses: 'المصروفات',
    netProfit: 'صافي الربح',
    avgTicket: 'متوسط التذكرة',
    revenueTrends: 'اتجاهات الإيرادات',
    recentTransactions: 'المعاملات الأخيرة',
    waitingForSale: 'في انتظار أول عملية بيع...',
    last7Days: 'آخر 7 أيام',
    today: 'اليوم',
    week: 'هذا الأسبوع',
    month: 'هذا الشهر',
    all: 'كل الوقت',
    custom: 'نطاق مخصص',
    lowStockAlerts: 'تنبيهات نقص المخزون',
    itemsRestock: 'عناصر تحتاج إلى إعادة تخزين',
    restockNow: 'إعادة التخزين الآن',
    inventoryValue: 'قيمة المخزون',
    payroll: 'كشوف المرتبات',
    remainingBalance: 'الرصيد المتبقي',
    topPerformers: 'أفضل الموظفين',
    topServices: 'أفضل الخدمات',
    topProducts: 'أفضل المنتجات',
    staffLeaderboard: 'لائحة الصدارة للموظفين',
    expenseBreakdown: 'تفصيل المصروفات',
    alertQty: 'كمية التنبيه',
    noRecords: 'لا توجد سجلات.',
    services: 'الخدمات',
    products: 'المنتجات',
    searchCatalog: 'البحث في الكتالوج...',
    scanBarcode: 'مسح الباركود',
    stopScanning: 'إيقاف المسح',
    cart: 'العربة',
    emptyCart: 'عربة فارغة',
    subtotal: 'المجموع الفرعي',
    discount: 'خصم',
    tax: 'ضريبة',
    total: 'الإجمالي',
    cash: 'نقدي',
    card: 'بطاقة',
    holdBill: 'تعليق الفاتورة',
    heldBills: 'الفواتير المعلقة',
    resume: 'استئناف',
    saleSuccess: 'نجاح البيع',
    orderCompleted: 'اكتمل الطلب.',
    shareReceipt: 'مشاركة الإيصال',
    downloadPdf: 'تنزيل PDF',
    startNewBill: 'بدء فاتورة جديدة',
    chooseProfessional: 'اختر المحترف...',
    walkInClient: 'عميل عابر',
    quickAddClient: 'إضافة عميل سريع',
    addSelectClient: 'إضافة واختيار العميل',
    name: 'الاسم',
    nameUr: 'الاسم (بالعربية)',
    nameUrPlaceholder: 'الاسم بالعربية',
    mobile: 'رقم الجوال',
    email: 'البريد الإلكتروني',
    optional: 'اختياري',
    shopPerformance: 'أداء المتجر',
    commissionReport: 'تقرير العمولة',
    payrollReport: 'إنشاء تقارير الرواتب حسب النطاق الزمني.',
    newExpense: 'مصروف جديد',
    history: 'السجل',
    periodRevenue: 'إيرادات الفترة',
    totalPayout: 'إجمالي الدفع',
    professional: 'المحترف',
    salesCount: 'عدد المبيعات',
    totalSales: 'إجمالي المبيعات',
    payout: 'الدفع',
    rate: 'النسبة',
    category: 'الفئة',
    amount: 'المبلغ',
    details: 'التفاصيل',
    addExpense: 'إضافة مصروف',
    smartInsights: 'رؤى ذكية (AI)',
    generateAdvice: 'إنشاء نصيحة',
    analyzing: 'جاري التحليل...',
    aiPrompt: 'انقر على \'إنشاء نصيحة\' للحصول على تحليل شخصي للأعمال.',
    noSalesPeriod: 'لا توجد مبيعات في هذه الفترة.',
    noteDetails: 'سجل أي تفاصيل...',
    exportReports: 'تصدير التقارير',
    downloadDaily: 'تنزيل يومي',
    downloadWeekly: 'تنزيل أسبوعي',
    downloadMonthly: 'تنزيل شهري',
    directory: 'الدليل',
    clientProfiles: 'ملفات العملاء والسجل.',
    addClient: 'إضافة عميل',
    searchClients: 'البحث عن عملاء...',
    visits: 'الزيارات',
    lifetime: 'مدى الحياة',
    lastSeen: 'آخر ظهور',
    stylePreferences: 'تفضيلات الأسلوب',
    noNotes: 'لا توجد ملاحظات.',
    date: 'التاريخ',
    items: 'العناصر',
    registerClient: 'تسجيل عميل',
    createProfile: 'إنشاء ملف تعريف',
    pickClient: 'اختر عميلاً لمراجعة سجل العناية الخاص به.',
    member: 'عضو',
    vip: 'شخصية هامة',
    teamHub: 'مركز الفريق',
    manageAccess: 'إدارة الوصول والأرباح.',
    addStaff: 'إضافة موظف',
    loginId: 'معرف الدخول',
    role: 'الدور',
    commission: 'عمولة',
    actions: 'إجراءات',
    editProfessional: 'تعديل المحترف',
    addToTeam: 'إضافة للفريق',
    fullName: 'الاسم الكامل',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    employee: 'موظف',
    admin: 'مسؤول',
    saveProfessional: 'حفظ المحترف',
    updateProfessional: 'تحديث المحترف',
    shopCatalog: 'كتالوج المتجر',
    updatePrices: 'تحديث الأسعار والمخزون.',
    newService: 'خدمة جديدة',
    newProduct: 'منتج جديد',
    inventory: 'المخزون',
    itemDetails: 'تفاصيل العنصر',
    stockStatus: 'حالة المخزون',
    price: 'السعر',
    editEntry: 'تعديل السجل',
    newEntry: 'سجل جديد',
    labelName: 'اسم الملصق',
    barcode: 'باركود',
    mins: 'دقائق',
    cost: 'التكلفة',
    initialStock: 'المخزون الأولي',
    saveChanges: 'حفظ التغييرات',
    unitsLeft: 'الوحدات المتبقية',
    session: 'جلسة',
    fineTune: 'ضبط المتجر والتواصل.',
    shopBranding: 'العلامة التجارية للمتجر واللغة',
    terminalIdentity: 'هوية المحطة',
    language: 'اللغة',
    countryCode: 'كود البلد الافتراضي',
    preferredCurrency: 'العملة المفضلة',
    taxCalculation: 'حساب الضريبة',
    taxRate: 'نسبة الضريبة (%)',
    receiptFooter: 'تذييل الإيصال',
    whatsAppSummaries: 'ملخصات واتساب',
    enableWhatsApp: 'تفعيل الإيصالات الرقمية عبر واتساب.',
    businessMobile: 'رقم جوال العمل',
    resetChanges: 'إعادة تعيين التغييرات',
    saveSettings: 'حفظ جميع الإعدادات',
    excluded: 'مستبعد',
    included: 'مشمول',
    customSymbol: 'رمز مخصص...',
    billingCycle: 'دورة الفوترة',
    billingDay: 'يوم بدء الشهر',
    dangerZone: 'منطقة الخطر',
    resetSales: 'إعادة تعيين سجل المبيعات',
    resetSalesDesc: 'حذف جميع سجلات المبيعات بشكل دائم. لا يمكن التراجع عن هذا الإجراء.',
    confirmReset: 'هل أنت متأكد تمامًا أنك تريد حذف جميع سجلات المبيعات؟',
    promoCodes: 'الرموز الترويجية والكوبونات',
    addPromo: 'إضافة رمز ترويجي',
    code: 'الرمز',
    discountType: 'نوع الخصم',
    value: 'القيمة',
    description: 'الوصف',
    fixed: 'مبلغ ثابت',
    percentage: 'نسبة مئوية (%)',
    deductExpenses: 'خصم مصاريف المتجر من العمولة',
    deductExpensesDesc: 'إذا تم تفعيله، سيتم طرح إجمالي مصاريف المتجر من الإيرادات قبل حساب عمولات الموظفين.',
    advancePayments: 'المدفوعات المقدمة',
    addAdvance: 'إضافة سلفة',
    payoutSummary: 'ملخص المدفوعات',
    netCommission: 'صافي العمولة',
    totalAdvances: 'إجمالي السلف',
    finalPayout: 'الدفعة النهائية',
    premiumAccess: 'الوصول المتميز للمحطة',
    securityKey: 'مفتاح الأمان',
    enterDashboard: 'دخول لوحة القيادة',
    authorizedUse: 'للاستخدام المصرح به فقط',
    contactAdmin: 'اتصل بمسؤول النظام',
    loyaltyProgram: 'برنامج الولاء',
    loyaltyProgramDesc: 'كافئ العملاء بنقاط على كل عملية شراء',
    pointsPerCurrencyHelp: 'مثال، 1 = اكسب نقطة واحدة لكل دولار تنفقه',
    minPointsRedeem: 'الحد الأدنى من النقاط للاستبدال',
    minPointsRedeemHelp: 'يحتاج العملاء إلى هذا العدد من النقاط على الأقل قبل التمكن من الاستبدال',
    pointValue: 'قيمة النقطة (الاستبدال)',
    pointValueHelp: 'مثال، نقطة واحدة = 0.01 خصم',
    howItWorks: 'كيف يعمل',
    loyaltyExplanation: 'يكتسب العملاء نقاطًا عند كل شراء. يمكنهم استبدالها عند الدفع بناءً على هذه الإعدادات.',
    reportingPeriod: 'فترة إعداد التقارير',
    billingCycleDescription: 'ستستخدم تقاريرك المالية ولوحة القيادة هذا اليوم كبداية لكل شهر عمل.',
    invalidLogin: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    stayLoggedIn: 'البقاء قيد تسجيل الدخول لمدة 30 يومًا',
    searchRefund: 'البحث عن معرف البيع للاسترداد...',
    splitPayment: 'تقسيم الدفع',
    holdResume: 'تعليق/استئناف',
    refunds: 'المستردات',
    loyaltyPoints: 'نقاط الولاء',
    suppliers: 'الموردون',
    onlineBooking: 'الحجز عبر الإنترنت',
    bookingSlug: 'رابط الحجز',
    enableBooking: 'تفعيل صفحة الحجز العامة',
    copyBookingLink: 'نسخ رابط الحجز',
    bookingLinkCopied: 'تم نسخ رابط الحجز!',
    approvalQueue: 'قائمة الانتظار للموافقة',
    confirmBooking: 'تأكيد الحجز',
    declineBooking: 'رفض الحجز',
    bookingStatusUnconfirmed: 'في انتظار الموافقة',
    bookingStatusConfirmed: 'مؤكد',
    cashDrawer: 'درج النقد',
    staffLoginLink: 'رابط دخول الموظفين',
    staffLoginDesc: 'صفحة تسجيل دخول مستقلة لأعضاء الفريق.',
    copyStaffLink: 'نسخ الرابط',
    staffLinkCopied: 'تم نسخ رابط الموظفين!',
    newSupplier: 'مورد جديد',
    addStockLog: 'سجل مخزون جديد',
    startingCash: 'النقد الأولي',
    endingCash: 'النقد النهائي',
    actualCash: 'النقد الفعلي',
    discrepancy: 'التفاوت',
    openDrawer: 'فتح الدرج',
    closeDrawer: 'إغلاق الدرج',
    loyaltyEnabled: 'تفعيل برنامج الولاء',
    pointsPerCurrency: 'النقاط لكل وحدة عملة',
    minPointsToRedeem: 'الحد الأدنى للاستبدال',
    customerPreferences: 'تفضيلات العميل',
    stockLogs: 'سجلات المخزون',
    adjustment: 'تعديل',
    restock: 'إعادة تخزين',
    damage: 'تالف',
    return: 'إرجاع',
    profitAndLoss: 'الأرباح والخسائر',
    taxSummary: 'ملخص الضرائب',
    exportCSV: 'تصدير CSV',
    supplierName: 'اسم المورد',
    contactPerson: 'جهة الاتصال',
    address: 'العنوان',
    phone: 'الهاتف',
    stock: 'المخزون',
    exportPDF: 'تصدير PDF',
    totalStockValue: 'إجمالي قيمة المخزون',
    netProfitMargin: 'هامش صافي الربح',
    costOfGoods: 'تكلفة البضائع',
    grossProfit: 'إجمالي الربح',
    noMatchingEntries: 'حاول تغيير بحثك أو إضافة سجل جديد.',
    confirmDeletion: 'تأكيد الحذف',
    permanentlyDeleteEntry: 'هل أنت متأكد أنك تريد حذف هذا السجل نهائيًا؟',
    noMatchingClients: 'لم يتم العثور على عملاء مطابقين.',
    last: 'الأخير',
    noRecordedTransactions: 'لا توجد معاملات مسجلة.',
    deleteClient: 'حذف العميل',
    permanentlyDeleteClient: 'هل أنت متأكد أنك تريد حذف ملف تعريف هذا العميل نهائيًا؟',
    transactionReceipt: 'إيصال المعاملة',
    overview: 'نظرة عامة',
    transactions: 'المعاملات',
    taxableRevenue: 'الإيرادات الخاضعة للضريبة',
    taxCollected: 'الضرائب المحصلة',
    taxLiability: 'الالتزام الضريبي',
    basedOn: 'بناءً على',
    deleteSelected: 'حذف المحدد',
    time: 'الوقت',
    action: 'إجراء',
    view: 'عرض',
    save: 'حفظ',
    delete: 'حذف',
    remove: 'إزالة',
    afterExpenseShare: 'بعد مشاركة المصاريف',
    drawerClosedMessage: 'درج النقد مغلق حاليًا. أدخل النقد الأولي لفتحه.',
    lastClosed: 'آخر إغلاق',
    expectedCash: 'النقد المتوقع',
    cashSales: 'مبيعات نقدية',
    cardSales: 'مبيعات بالبطاقة',
    splitSales: 'مبيعات مقسمة',
    totalSessionRevenue: 'إجمالي إيرادات الجلسة',
    deleteData: 'حذف البيانات',
    confirmDeleteTransactions: 'هل أنت متأكد أنك تريد حذف هذه المعاملات؟ لا يمكن التراجع عن هذا الإجراء.',
    selectMonth: 'اختر الشهر',
    selectYear: 'اختر السنة',
    database: 'قاعدة البيانات',
    online: 'متصل',
    offline: 'غير متصل',
    shopManagerAdmin: 'مسؤول مدير المتجر',
    thankYouChoosingUs: 'شكرا لاختيارك لنا!',
    hair: 'شعر',
    beard: 'لحية',
    shave: 'حلاقة',
    face: 'وجه',
    staffAvailability: 'ساعات العمل',
    closed: 'مغلق',
    noActivePromoCodes: 'لا توجد رموز ترويجية نشطة.',
    monthlySalesCycle: 'دورة المبيعات الشهرية',
    configureBusinessMonth: 'قم بتكوين وقت بدء شهر العمل الخاص بك.',
    autoResetEnabled: 'تمكين إعادة التعيين التلقائي:',
    autoResetDescription: 'في اليوم {day} من كل شهر، سيتم تحديث تقاريرك لإظهار البيانات الجديدة.',
    globalSettingsAdminOnly: 'يتم إدارة الإعدادات العامة من قبل المسؤولين.',
    databaseDiagnostics: 'تشخيص قاعدة البيانات',
    verifyCloudConnection: 'تحقق من اتصالك السحابي.',
    status: 'الحالة',
    errorMessage: 'رسالة الخطأ',
    configurationCheck: 'التحقق من التكوين',
    premiumGrooming: 'إدارة الأعمال المميزة',
    pro: 'محترف:',
    client: 'العميل:',
    offlineModeActive: 'وضع غير متصل نشط',
    offlineModeMessage: 'يمكنك إنشاء فواتير، لكنها لن تتم مزامنتها حتى يعود الاتصال.',
    searchReturnMessage: 'ابحث عن معرف البيع لإيجاد معاملات الاسترداد.',
    clientStaffInfo: 'عميل: {client} • موظف: {staff}',
    noSalesFound: 'لا توجد مبيعات مطابقة',
    enterSaleIdRefund: 'أدخل معرف البيع لبدء الاسترداد.',
    itemsToReturn: 'العناصر المراد إرجاعها',
    selectItemsRefund: 'حدد العناصر لاسترداد كامل أو جزئي',
    refundTotal: 'إجمالي الاسترداد',
    held: 'معلق',
    selectToResume: 'اختر للاستئناف',
    loyaltyPointsUsed: 'النقاط المستخدمة',
    loyaltyPointsAvailable: 'النقاط المتاحة',
    cashAmount: 'المبلغ النقدي',
    cardAmount: 'مبلغ البطاقة',
    cancelSplit: 'إلغاء التقسيم',
    quickDiscount: 'خصم سريع',
    itemNotInCatalog: 'العنصر ليس في الكتالوج.',
    alignBarcode: 'قم بمحاذاة الباركود أفقيًا',
    discardHeldBill: 'تجاهل الفاتورة المعلقة',
    confirmDiscardHeldBill: 'هل أنت متأكد من تجاهل هذه الفاتورة؟',
    commandCenter: 'مركز القيادة',
    deleteProfessional: 'حذف المحترف',
    permanentlyRemoveTeamMember: 'إزالة عضو الفريق نهائيًا؟',
    somethingWentWrong: 'حدث خطأ ما',
    unexpectedError: 'حدث خطأ غير متوقع في هذا القسم.',
    error: 'خطأ',
    notificationSettings: 'إعدادات الإشعارات',
    testNotification: 'إشعار تجريبي',
    updatePermissions: 'تحديث الأذونات',
    notificationStatus: 'حالة الإشعارات',
    notificationGranted: 'مسموح',
    notificationDenied: 'مرفوض',
    notificationDefault: 'انقر للطلب',
    autoWhatsapp: 'واتساب تلقائي',
    addSale: 'إضافة بيع',
    recentSales: 'المبيعات الأخيرة',
    salaryAndTips: 'الراتب والبقشيش',
    baseSalaryLabel: 'الأساسي: ',
    tipsLabel: 'البقشيش: ',
    markPaid: 'تسجيل كمدفوع',
    confirmPaid: 'تأكيد',
    cancel: 'إلغاء',
    paid: 'مدفوع',
    confirmDelete: 'تأكيد الحذف',
    tipAmount: 'قيمة البقشيش',
    addTip: 'إضافة بقشيش',
    removeTip: 'إزالة البقشيش',
    baseSalary: 'الراتب الأساسي',
    monthlyFixedSalary: 'راتب شهري ثابت (اختياري)',
    onlyLettersNumbersHyphens: 'يُسمح فقط بالحروف والأرقام والشرطات',
    startYourShift: 'ابدأ نوبتك.',
    loginToAccess: 'تسجيل الدخول للوصول إلى نقطة البيع والمواعيد.',
    sessionDetails: 'تفاصيل الجلسة',
    autoExpires12h: 'تنتهي تلقائيًا بعد 12 ساعة',
    autoLogoutSecurity: 'سيتم تسجيل خروجك تلقائيًا للأمان',
    credentialsEncrypted: 'البيانات مشفرة. اتصل بالمدير إذا تم قفل الحساب.',
    staffSignInTitle: 'تسجيل دخول الموظفين',
    enterShiftCredentials: 'أدخل بيانات نوبتك أدناه.',
    sessionExpiresSecurity: 'تنتهي الجلسة تلقائيًا بعد 12 ساعة للأمان.',
    verifying: 'جاري التحقق...',
    shopNotFound: 'المتجر غير موجود أو غير نشط.',
    staffRecordsNotFound: 'سجلات الموظفين غير موجودة. اتصل بالمدير.',
    loading: 'جاري التحميل...',

},
  hi: {
    dashboard: 'डैशबोर्ड',
    pos: 'पीओएस',
    catalog: 'कैटलॉग',
    customers: 'ग्राहक',
    staff: 'स्टाफ प्रबंधन',
    finance: 'वित्त',
    settings: 'सेटिंग्स',
    appointments: 'अपॉइंटमेंट',
    logout: 'लॉग आउट',
    shopStatus: 'दुकान की स्थिति',
    terminalLive: 'टर्मिनल लाइव',
    transactionHistory: 'लेन-देन का इतिहास',
    performanceInsights: 'प्रदर्शन की जानकारी',
    welcomeBack: 'वापसी पर स्वागत है! यहाँ आपकी दुकान की स्थिति है।',
    revenue: 'राजस्व',
    expenses: 'खर्च',
    netProfit: 'शुद्ध लाभ',
    avgTicket: 'औसत टिकट',
    revenueTrends: 'राजस्व रुझान',
    recentTransactions: 'हाल के लेन-देन',
    waitingForSale: 'पहली बिक्री की प्रतीक्षा...',
    last7Days: 'पिछले 7 दिन',
    today: 'आज',
    week: 'इस सप्ताह',
    month: 'इस महीने',
    all: 'सभी समय',
    custom: 'कस्टम रेंज',
    lowStockAlerts: 'कम स्टॉक अलर्ट',
    itemsRestock: 'आइटम जिन्हें रीस्टॉक करना है',
    restockNow: 'अभी रीस्टॉक करें',
    inventoryValue: 'इन्वेंटरी वैल्यू',
    payroll: 'पेरोल',
    remainingBalance: 'शेष राशि',
    topPerformers: 'शीर्ष कलाकार',
    topServices: 'शीर्ष सेवाएँ',
    topProducts: 'शीर्ष उत्पाद',
    staffLeaderboard: 'स्टाफ लीडरबोर्ड',
    expenseBreakdown: 'खर्च का विवरण',
    alertQty: 'अलर्ट मात्रा',
    noRecords: 'कोई रिकॉर्ड नहीं मिला।',
    services: 'सेवाएँ',
    products: 'उत्पाद',
    searchCatalog: 'कैटलॉग खोजें...',
    scanBarcode: 'बारकोड स्कैन करें',
    stopScanning: 'स्कैनिंग रोकें',
    cart: 'कार्ट',
    emptyCart: 'खाली कार्ट',
    subtotal: 'उप-कुल',
    discount: 'छूट',
    tax: 'कर',
    total: 'कुल',
    cash: 'नकद',
    card: 'कार्ड',
    holdBill: 'बिल होल्ड करें',
    heldBills: 'होल्ड किए गए बिल',
    resume: 'फिर से शुरू करें',
    saleSuccess: 'बिक्री सफल',
    orderCompleted: 'ऑर्डर पूरा हुआ।',
    shareReceipt: 'रसीद साझा करें',
    downloadPdf: 'पीडीएफ डाउनलोड करें',
    startNewBill: 'नया बिल शुरू करें',
    chooseProfessional: 'पेशेवर चुनें...',
    walkInClient: 'वॉक-इन ग्राहक',
    quickAddClient: 'त्वरित ग्राहक जोड़ें',
    addSelectClient: 'ग्राहक जोड़ें और चुनें',
    name: 'नाम',
    nameUr: 'नाम (स्थानीय भाषा)',
    nameUrPlaceholder: 'स्थानीय भाषा में नाम',
    mobile: 'मोबाइल',
    email: 'ईमेल',
    optional: 'वैकल्पिक',
    shopPerformance: 'दुकान का प्रदर्शन',
    commissionReport: 'कमीशन रिपोर्ट',
    payrollReport: 'तिथि सीमा के अनुसार पेरोल रिपोर्ट जनरेट करें।',
    newExpense: 'नया खर्च',
    history: 'इतिहास',
    periodRevenue: 'अवधि राजस्व',
    totalPayout: 'कुल भुगतान',
    professional: 'पेशेवर',
    salesCount: 'बिक्री की संख्या',
    totalSales: 'कुल बिक्री',
    payout: 'भुगतान',
    rate: 'दर',
    category: 'श्रेणी',
    amount: 'राशि',
    details: 'विवरण',
    addExpense: 'खर्च जोड़ें',
    smartInsights: 'स्मार्ट एआई इनसाइट्स',
    generateAdvice: 'सलाह जनरेट करें',
    analyzing: 'विश्लेषण किया जा रहा है...',
    aiPrompt: 'व्यक्तिगत व्यापार विश्लेषण के लिए \'सलाह जनरेट करें\' पर टैप करें।',
    noSalesPeriod: 'इस अवधि में कोई बिक्री नहीं मिली।',
    noteDetails: 'कोई विवरण नोट करें...',
    exportReports: 'रिपोर्ट एक्सपोर्ट करें',
    downloadDaily: 'दैनिक डाउनलोड करें',
    downloadWeekly: 'साप्ताहिक डाउनलोड करें',
    downloadMonthly: 'मासिक डाउनलोड करें',
    directory: 'निर्देशिका',
    clientProfiles: 'ग्राहक प्रोफाइल और इतिहास।',
    addClient: 'ग्राहक जोड़ें',
    searchClients: 'ग्राहक खोजें...',
    visits: 'विजिट्स',
    lifetime: 'जीवनकाल',
    lastSeen: 'अंतिम बार देखा गया',
    stylePreferences: 'शैली प्राथमिकताएँ',
    noNotes: 'कोई नोट्स नहीं।',
    date: 'तारीख',
    items: 'आइटम',
    registerClient: 'ग्राहक पंजीकृत करें',
    createProfile: 'प्रोफाइल बनाएं',
    pickClient: 'ग्रूमिंग इतिहास की समीक्षा के लिए एक ग्राहक चुनें।',
    member: 'सदस्य',
    vip: 'वीआईपी',
    teamHub: 'टीम हब',
    manageAccess: 'पहुंच और कमाई प्रबंधित करें।',
    addStaff: 'स्टाफ जोड़ें',
    loginId: 'लॉगिन आईडी',
    role: 'भूमिका',
    commission: 'कमीशन',
    actions: 'कार्रवाइयां',
    editProfessional: 'पेशेवर संपादित करें',
    addToTeam: 'टीम में जोड़ें',
    fullName: 'पूरा नाम',
    username: 'यूज़रनेम',
    password: 'पासवर्ड',
    employee: 'कर्मचारी',
    admin: 'व्यवस्थापक',
    saveProfessional: 'पेशेवर सहेजें',
    updateProfessional: 'पेशेवर अपडेट करें',
    shopCatalog: 'दुकान कैटलॉग',
    updatePrices: 'कीमतें और स्टॉक अपडेट करें।',
    newService: 'नई सेवा',
    newProduct: 'नया उत्पाद',
    inventory: 'इन्वेंटरी',
    itemDetails: 'आइटम विवरण',
    stockStatus: 'स्टॉक की स्थिति',
    price: 'कीमत',
    editEntry: 'एंट्री संपादित करें',
    newEntry: 'नई एंट्री',
    labelName: 'लेबल का नाम',
    barcode: 'बारकोड',
    mins: 'मिनट',
    cost: 'लागत',
    initialStock: 'प्रारंभिक स्टॉक',
    saveChanges: 'परिवर्तन सहेजें',
    unitsLeft: 'इकाइयां शेष',
    session: 'सत्र',
    fineTune: 'अपनी दुकान और संचार को फाइन-ट्यून करें।',
    shopBranding: 'दुकान ब्रांडिंग और स्थानीयकरण',
    terminalIdentity: 'टर्मिनल पहचान',
    language: 'भाषा',
    countryCode: 'डिफ़ॉल्ट देश कोड',
    preferredCurrency: 'पसंदीदा मुद्रा',
    taxCalculation: 'कर की गणना',
    taxRate: 'कर की दर (%)',
    receiptFooter: 'रसीद पाद लेख',
    whatsAppSummaries: 'व्हाट्सएप सारांश',
    enableWhatsApp: 'व्हाट्सएप के माध्यम से डिजिटल रसीदें सक्षम करें।',
    businessMobile: 'व्यवसाय मोबाइल नंबर',
    resetChanges: 'परिवर्तन रीसेट करें',
    saveSettings: 'सभी सेटिंग्स सहेजें',
    excluded: 'शामिल नहीं',
    included: 'शामिल',
    customSymbol: 'कस्टम प्रतीक...',
    billingCycle: 'बिलिंग चक्र',
    billingDay: 'महीने का प्रारंभ दिन',
    dangerZone: 'डेंजर ज़ोन',
    resetSales: 'बिक्री इतिहास रीसेट करें',
    resetSalesDesc: 'सभी बिक्री इतिहास को स्थायी रूप से हटा दें। इसे पूर्ववत नहीं किया जा सकता है।',
    confirmReset: 'क्या आप वाकई सभी बिक्री रिकॉर्ड हटाना चाहते हैं?',
    promoCodes: 'प्रोमो कोड और कूपन',
    addPromo: 'प्रोमो कोड जोड़ें',
    code: 'कोड',
    discountType: 'छूट का प्रकार',
    value: 'मूल्य',
    description: 'विवरण',
    fixed: 'निश्चित राशि',
    percentage: 'प्रतिशत (%)',
    deductExpenses: 'दुकान के खर्चों को कमीशन से घटाएं',
    deductExpensesDesc: 'यदि सक्षम है, तो स्टाफ कमीशन की गणना करने से पहले राजस्व से कुल दुकान के खर्चों को घटाया जाएगा।',
    advancePayments: 'अग्रिम भुगतान',
    addAdvance: 'अग्रिम जोड़ें',
    payoutSummary: 'भुगतान सारांश',
    netCommission: 'शुद्ध कमीशन',
    totalAdvances: 'कुल अग्रिम',
    finalPayout: 'अंतिम भुगतान',
    premiumAccess: 'प्रीमियम टर्मिनल एक्सेस',
    securityKey: 'सुरक्षा कुंजी',
    enterDashboard: 'डैशबोर्ड में प्रवेश करें',
    authorizedUse: 'केवल अधिकृत उपयोग',
    contactAdmin: 'सिस्टम एडमिन से संपर्क करें',
    loyaltyProgram: 'लॉयल्टी प्रोग्राम',
    loyaltyProgramDesc: 'हर खरीदारी पर ग्राहकों को अंक से पुरस्कृत करें',
    pointsPerCurrencyHelp: 'उदा., 1 = खर्च किए गए प्रत्येक $1 पर 1 अंक अर्जित करें',
    minPointsRedeem: 'रिडीम करने के लिए न्यूनतम अंक',
    minPointsRedeemHelp: 'रिडीम करने से पहले ग्राहकों को कम से कम इतने अंकों की आवश्यकता होती है',
    pointValue: 'अंक मूल्य (रिडेम्पशन)',
    pointValueHelp: 'उदा., 1 अंक = 0.01 छूट',
    howItWorks: 'यह कैसे काम करता है',
    loyaltyExplanation: 'ग्राहक हर खरीदारी पर अंक अर्जित करते हैं। वे इन सेटिंग्स के आधार पर चेकआउट के समय उन्हें रिडीम कर सकते हैं।',
    reportingPeriod: 'रिपोर्टिंग अवधि',
    billingCycleDescription: 'आपकी वित्तीय रिपोर्ट और डैशबोर्ड इस दिन का उपयोग प्रत्येक व्यावसायिक माह के आरंभ के रूप में करेंगे।',
    invalidLogin: 'अमान्य यूज़रनेम या पासवर्ड',
    stayLoggedIn: '30 दिनों तक लॉग इन रहें',
    searchRefund: 'रिफंड के लिए सेल आईडी खोजें...',
    splitPayment: 'विभाजित भुगतान',
    holdResume: 'होल्ड/रिज्यूम',
    refunds: 'रिफंड',
    loyaltyPoints: 'लॉयल्टी अंक',
    suppliers: 'आपूर्तिकर्ता',
    onlineBooking: 'ऑनलाइन बुकिंग',
    bookingSlug: 'बुकिंग लिंक स्लग',
    enableBooking: 'सार्वजनिक बुकिंग पृष्ठ सक्षम करें',
    copyBookingLink: 'बुकिंग लिंक कॉपी करें',
    bookingLinkCopied: 'बुकिंग लिंक कॉपी हो गया!',
    approvalQueue: 'अनुमोदन कतार',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    declineBooking: 'बुकिंग अस्वीकार करें',
    bookingStatusUnconfirmed: 'अनुमोदन की प्रतीक्षा में',
    bookingStatusConfirmed: 'पुष्टि की गई',
    cashDrawer: 'कैश दराज',
    staffLoginLink: 'स्टाफ लॉगिन लिंक',
    staffLoginDesc: 'टीम के सदस्यों के लिए स्वतंत्र लॉगिन पृष्ठ।',
    copyStaffLink: 'लिंक कॉपी करें',
    staffLinkCopied: 'स्टाफ लॉगिन लिंक कॉपी हो गया!',
    newSupplier: 'नया आपूर्तिकर्ता',
    addStockLog: 'नया स्टॉक लॉग',
    startingCash: 'प्रारंभिक नकद',
    endingCash: 'अंतिम नकद',
    actualCash: 'वास्तविक नकद',
    discrepancy: 'विसंगति',
    openDrawer: 'दराज खोलें',
    closeDrawer: 'दराज बंद करें',
    loyaltyEnabled: 'लॉयल्टी प्रोग्राम सक्षम करें',
    pointsPerCurrency: 'प्रति मुद्रा इकाई अंक',
    minPointsToRedeem: 'रिडीम करने के लिए न्यूनतम अंक',
    customerPreferences: 'ग्राहक प्राथमिकताएं',
    stockLogs: 'स्टॉक लॉग',
    adjustment: 'समायोजन',
    restock: 'रीस्टॉक',
    damage: 'क्षति',
    return: 'वापसी',
    profitAndLoss: 'लाभ और हानि',
    taxSummary: 'कर सारांश',
    exportCSV: 'CSV एक्सपोर्ट करें',
    supplierName: 'आपूर्तिकर्ता का नाम',
    contactPerson: 'संपर्क व्यक्ति',
    address: 'पता',
    phone: 'फोन',
    stock: 'स्टॉक',
    exportPDF: 'PDF एक्सपोर्ट करें',
    totalStockValue: 'कुल स्टॉक वैल्यू',
    netProfitMargin: 'शुद्ध लाभ मार्जिन',
    costOfGoods: 'माल की लागत',
    grossProfit: 'सकल लाभ',
    noMatchingEntries: 'अपनी खोज बदलने का प्रयास करें या एक नई प्रविष्टि जोड़ें।',
    confirmDeletion: 'हटाने की पुष्टि करें',
    permanentlyDeleteEntry: 'क्या आप वाकई इस प्रविष्टि को स्थायी रूप से हटाना चाहते हैं?',
    noMatchingClients: 'कोई मेल खाने वाले ग्राहक नहीं मिले।',
    last: 'अंतिम',
    noRecordedTransactions: 'कोई रिकॉर्ड किए गए लेन-देन नहीं।',
    deleteClient: 'ग्राहक हटाएं',
    permanentlyDeleteClient: 'क्या आप वाकई इस ग्राहक प्रोफ़ाइल को स्थायी रूप से हटाना चाहते हैं?',
    transactionReceipt: 'लेन-देन रसीद',
    overview: 'अवलोकन',
    transactions: 'लेन-देन',
    taxableRevenue: 'कर योग्य राजस्व',
    taxCollected: 'एकत्रित कर',
    taxLiability: 'कर देयता',
    basedOn: 'के आधार पर',
    deleteSelected: 'चयनित को हटाएं',
    time: 'समय',
    action: 'कार्रवाई',
    view: 'देखें',
    save: 'सहेजें',
    delete: 'हटाएं',
    remove: 'निकालें',
    afterExpenseShare: 'खर्च साझा करने के बाद',
    drawerClosedMessage: 'कैश दराज वर्तमान में बंद है। इसे खोलने के लिए प्रारंभिक नकद दर्ज करें।',
    lastClosed: 'अंतिम बार बंद',
    expectedCash: 'अपेक्षित नकद',
    cashSales: 'नकद बिक्री',
    cardSales: 'कार्ड बिक्री',
    splitSales: 'विभाजित बिक्री',
    totalSessionRevenue: 'कुल सत्र राजस्व',
    deleteData: 'डेटा हटाएं',
    confirmDeleteTransactions: 'क्या आप वाकई इन लेन-देन को हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।',
    selectMonth: 'महीना चुनें',
    selectYear: 'वर्ष चुनें',
    database: 'डेटाबेस',
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    shopManagerAdmin: 'दुकान प्रबंधक व्यवस्थापक',
    thankYouChoosingUs: 'हमें चुनने के लिए धन्यवाद!',
    hair: 'बाल',
    beard: 'दाढ़ी',
    shave: 'शेव',
    face: 'चेहरा',
    staffAvailability: 'काम के घंटे',
    closed: 'छुट्टी',
    noActivePromoCodes: 'कोई सक्रिय प्रोमो कोड नहीं।',
    monthlySalesCycle: 'मासिक बिक्री चक्र',
    configureBusinessMonth: 'कॉन्फ़िगर करें कि आपका व्यावसायिक माह कब शुरू होता है।',
    autoResetEnabled: 'ऑटो-रीसेट सक्षम:',
    autoResetDescription: 'प्रत्येक महीने के दिन {day} पर, आपकी रिपोर्ट नए डेटा दिखाने के लिए ताज़ा होंगी।',
    globalSettingsAdminOnly: 'वैश्विक सेटिंग्स का प्रबंधन व्यवस्थापकों द्वारा किया जाता है।',
    databaseDiagnostics: 'डेटाबेस डायग्नोस्टिक्स',
    verifyCloudConnection: 'अपना क्लाउड कनेक्शन सत्यापित करें।',
    status: 'स्थिति',
    errorMessage: 'त्रुटि संदेश',
    configurationCheck: 'कॉन्फ़िगरेशन जांच',
    premiumGrooming: 'प्रीमियम बिजनेस मैनेजमेंट',
    pro: 'प्रो:',
    client: 'ग्राहक:',
    offlineModeActive: 'ऑफ़लाइन मोड सक्रिय',
    offlineModeMessage: 'आप अभी भी बिल बना सकते हैं, लेकिन कनेक्शन वापस आने तक वे सिंक नहीं होंगे।',
    searchReturnMessage: 'रिटर्न खोजने के लिए सेल आईडी खोजें।',
    clientStaffInfo: 'ग्राहक: {client} • स्टाफ: {staff}',
    noSalesFound: 'कोई मेल खाने वाली बिक्री नहीं मिली',
    enterSaleIdRefund: 'रिफंड शुरू करने के लिए सेल आईडी दर्ज करें।',
    itemsToReturn: 'लौटाए जाने वाले आइटम',
    selectItemsRefund: 'पूर्ण या आंशिक रिफंड के लिए आइटम चुनें',
    refundTotal: 'रिफंड कुल',
    held: 'होल्ड पर',
    selectToResume: 'फिर से शुरू करने के लिए चुनें',
    loyaltyPointsUsed: 'उपयोग किए गए अंक',
    loyaltyPointsAvailable: 'उपलब्ध अंक',
    cashAmount: 'नकद राशि',
    cardAmount: 'कार्ड राशि',
    cancelSplit: 'स्प्लिट रद्द करें',
    quickDiscount: 'त्वरित छूट',
    itemNotInCatalog: 'आइटम कैटलॉग में नहीं है।',
    alignBarcode: 'बारकोड को क्षैतिज रूप से संरेखित करें',
    discardHeldBill: 'होल्ड किया गया बिल त्यागें',
    confirmDiscardHeldBill: 'क्या आप वाकई इस बिल को छोड़ना चाहते हैं?',
    commandCenter: 'कमांड सेंटर',
    deleteProfessional: 'पेशेवर हटाएं',
    permanentlyRemoveTeamMember: 'टीम के सदस्य को स्थायी रूप से निकालें?',
    somethingWentWrong: 'कुछ गलत हो गया',
    unexpectedError: 'इस अनुभाग में एक अप्रत्याशित त्रुटि आई।',
    error: 'त्रुटि',
    notificationSettings: 'अधिसूचना सेटिंग्स',
    testNotification: 'परीक्षण अधिसूचना',
    updatePermissions: 'अनुमतियाँ अपडेट करें',
    notificationStatus: 'अधिसूचना स्थिति',
    notificationGranted: 'स्वीकृत',
    notificationDenied: 'अस्वीकृत',
    notificationDefault: 'अनुरोध के लिए क्लिक करें',
    autoWhatsapp: 'स्वचालित व्हाट्सएप',
    addSale: 'बिक्री जोड़ें',
    recentSales: 'हाल की बिक्री',
    salaryAndTips: 'वेतन और टिप्स',
    baseSalaryLabel: 'मूल: ',
    tipsLabel: 'टिप्स: ',
    markPaid: 'भुगतान करें',
    confirmPaid: 'पुष्टि करें',
    cancel: 'रद्द करें',
    paid: 'भुगतान किया',
    confirmDelete: 'हटाने की पुष्टि करें',
    tipAmount: 'टिप राशि',
    addTip: 'टिप जोड़ें',
    removeTip: 'टिप निकालें',
    baseSalary: 'मूल वेतन',
    monthlyFixedSalary: 'मासिक निश्चित वेतन (वैकल्पिक)',
    onlyLettersNumbersHyphens: 'केवल अक्षर, संख्याएं और हाइफ़न',
    startYourShift: 'अपनी शिफ्ट शुरू करें।',
    loginToAccess: 'पहुंच प्राप्त करने के लिए लॉग इन करें।',
    sessionDetails: 'सत्र विवरण',
    autoExpires12h: '12 घंटे बाद स्वतः समाप्त',
    autoLogoutSecurity: 'सुरक्षा के लिए स्वचालित लॉग आउट',
    credentialsEncrypted: 'क्रेडेंशियल एन्क्रिप्टेड हैं।',
    staffSignInTitle: 'स्टाफ साइन इन',
    enterShiftCredentials: 'नीचे क्रेडेंशियल दर्ज करें।',
    sessionExpiresSecurity: 'सत्र 12 घंटे बाद समाप्त होता है।',
    verifying: 'सत्यापन हो रहा है...',
    shopNotFound: 'दुकान नहीं मिली या निष्क्रिय है।',
    staffRecordsNotFound: 'कर्मचारी रिकॉर्ड नहीं मिले।',
    loading: 'लोड हो रहा है...',
  },
};

export const INITIAL_SERVICES: Service[] = [
  { id: 's1', name: 'Classic Haircut', nameUr: 'کلاسک ہیئر کٹ', price: 35, duration: 30, category: 'Hair' },
  { id: 's2', name: 'Skin Fade', nameUr: 'اسکن فیڈ', price: 45, duration: 45, category: 'Hair' },
  { id: 's3', name: 'Beard Trim', nameUr: 'داڑھی کی تراش خراش', price: 20, duration: 20, category: 'Beard' },
  { id: 's4', name: 'Luxury Shave', nameUr: 'لگژری شیو', price: 50, duration: 60, category: 'Shave' },
  { id: 's5', name: 'Kid\'s Cut', nameUr: 'بچوں کی کٹنگ', price: 25, duration: 30, category: 'Hair' },
  { id: 's6', name: 'Head Shave', nameUr: 'سر منڈوانا', price: 30, duration: 30, category: 'Hair' },
];

export const INITIAL_PRODUCTS: Product[] = [
  { id: 'p1', name: 'Pomade Matte', nameUr: 'پومیڈ میٹ', price: 18, cost: 8, stock: 24, barcode: '123456789012', lowStockThreshold: 15 },
  { id: 'p2', name: 'Beard Oil', nameUr: 'داڑھی کا تیل', price: 22, cost: 10, stock: 15, barcode: '098765432109', lowStockThreshold: 15 },
  { id: 'p3', name: 'Aftershave Balm', nameUr: 'آفٹر شیو بام', price: 25, cost: 12, stock: 10, barcode: '112233445566', lowStockThreshold: 15 },
  { id: 'p4', name: 'Texture Spray', nameUr: 'ٹیکسچر سپرے', price: 20, cost: 9, stock: 8, barcode: '665544332211', lowStockThreshold: 15 },
];

export const INITIAL_STAFF: Staff[] = [
  { id: 'st1', name: 'Admin User', role: 'admin', commission: 0, username: '1234', password: '1234', isFallback: true },
  { id: 'st2', name: 'Alex Rivers', role: 'employee', commission: 40, username: 'alex', password: 'password123', isFallback: true },
];

export const INITIAL_EXPENSES: Expense[] = [
  { id: 'e1', date: '2024-05-01', category: 'Rent', amount: 2000, description: 'Monthly Shop Rent' },
  { id: 'e2', date: '2024-05-02', category: 'Utilities', amount: 350, description: 'Electricity & Water' },
  { id: 'e3', date: '2024-05-05', category: 'Supplies', amount: 150, description: 'Towels & Cleaning' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'John Smith', phone: '555-0101', email: 'john@example.com', notes: 'Likes a low taper fade.', createdAt: '2024-01-15', loyaltyPoints: 150 },
  { id: 'c2', name: 'Marcus Brown', phone: '555-0102', email: 'marcus@example.com', notes: 'Grows beard long.', createdAt: '2024-02-20', loyaltyPoints: 85 },
];
